In [99]:
import sqlalchemy
from sqlalchemy import MetaData, create_engine, inspect, Table, Column, Integer, String
import pandas as pd
import csv, os
import psycopg2
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [101]:
#Database Connection: SQLAlchemy
url = 'postgresql://{user}:{passwd}@{host}:{port}/{db}'.format(
user='postgres', passwd='Angybix6355', host='localhost', port='5432', db='country_db') 
# user='postgres', passwd='OO00ZZ33', host='localhost', port='5432', db='country_db')
engine = sqlalchemy.create_engine(url)
connection = engine.connect()  

Session = sessionmaker(bind = engine)
session = Session()
inspector = inspect(engine)

In [102]:
# United Nations: Extraction
UN_data_file = "../Selected Data/UN_Data_Country_Profiles/country_profile_variables.csv"
UN_data_df = pd.read_csv(UN_data_file, encoding="ISO-8859-1")
UN_data_df.head()

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99

In [103]:

# Set Index
UN_data_df.set_index('country', inplace = True)
# Display all columns
UN_data_df.columns

Index(['Region', 'Surface area (km2)', 'Population in thousands (2017)',
       'Population density (per km2, 2017)', 'Sex ratio (m per 100 f, 2017)',
       'GDP: Gross domestic product (million current US$)',
       'GDP growth rate (annual %, const. 2005 prices)',
       'GDP per capita (current US$)', 'Economy: Agriculture (% of GVA)',
       'Economy: Industry (% of GVA)',
       'Economy: Services and other activity (% of GVA)',
       'Employment: Agriculture (% of employed)',
       'Employment: Industry (% of employed)',
       'Employment: Services (% of employed)',
       'Unemployment (% of labour force)',
       'Labour force participation (female/male pop. %)',
       'Agricultural production index (2004-2006=100)',
       'Food production index (2004-2006=100)',
       'International trade: Exports (million US$)',
       'International trade: Imports (million US$)',
       'International trade: Balance (million US$)',
       'Balance of payments, current account (million US$)',
       'Population growth rate (average annual %)',
       'Urban population (% of total population)',
       'Urban population growth rate (average annual %)',
       'Fertility rate, total (live births per woman)',
       'Life expectancy at birth (females/males, years)',
       'Population age distribution (0-14 / 60+ years, %)',
       'International migrant stock (000/% of total pop.)',
       'Refugees and others of concern to UNHCR (in thousands)',
       'Infant mortality rate (per 1000 live births',
       'Health: Total expenditure (% of GDP)',
       'Health: Physicians (per 1000 pop.)',
       'Education: Government expenditure (% of GDP)',
       'Education: Primary gross enrol. ratio (f/m per 100 pop.)',
       'Education: Secondary gross enrol. ratio (f/m per 100 pop.)',
       'Education: Tertiary gross enrol. ratio (f/m per 100 pop.)',
       'Seats held by women in national parliaments %',
       'Mobile-cellular subscriptions (per 100 inhabitants)',
       'Mobile-cellular subscriptions (per 100 inhabitants).1',
       'Individuals using the Internet (per 100 inhabitants)',
       'Threatened species (number)', 'Forested area (% of land area)',
       'CO2 emission estimates (million tons/tons per capita)',
       'Energy production, primary (Petajoules)',
       'Energy supply per capita (Gigajoules)',
       'Pop. using improved drinking water (urban/rural, %)',
       'Pop. using improved sanitation facilities (urban/rural, %)',
       'Net Official Development Assist. received (% of GNI)'],
      dtype='object')

In [104]:
# United Nations: Transformation
UN_data_cols = ["Region", 
                "Population in thousands (2017)", 
                "Population density (per km2, 2017)", 
                "Sex ratio (m per 100 f, 2017)", 
                "GDP: Gross domestic product (million current US$)", 
                "GDP per capita (current US$)", 
                "Unemployment (% of labour force)", 
                "Population growth rate (average annual %)", 
                "Fertility rate, total (live births per woman)"]
UN_data_transformed= UN_data_df[UN_data_cols].copy()

UN_data_transformed = UN_data_transformed.rename(columns={
                                                        "Population in thousands (2017)": "pop_in_1000s", 
                                                        "Population density (per km2, 2017)": "pop_dens_per_sqkm", 
                                                        "Sex ratio (m per 100 f, 2017)": "males_per_100_fem", 
                                                        "GDP: Gross domestic product (million current US$)": "GDP_in_mil_dol", 
                                                        "GDP per capita (current US$)": "GDP_per_cap_in_mil", 
                                                        "Unemployment (% of labour force)": "unemploy_perct",
                                                        "Population growth rate (average annual %)": "pop_growth_rate_perct",
                                                        "Fertility rate, total (live births per woman)": "live_births_per_woman"
                                                        })
UN_data_transformed.head()

,Region,pop_in_1000s,pop_dens_per_sqkm,males_per_100_fem,GDP_in_mil_dol,GDP_per_cap_in_mil,unemploy_perct,pop_growth_rate_perct,live_births_per_woman
country,,,,,,,,,
Afghanistan,SouthernAsia,35530,54.4,106.3,20270,623.2,8.6,3.2,5.3
Albania,SouthernEurope,2930,106.9,101.9,11541,3984.2,15.8,-0.1,1.7
Algeria,NorthernAfrica,41318,17.3,102.0,164779,4154.1,11.4,2.0,3.0
American Samoa,Polynesia,56,278.2,103.6,-99,-99.0,...,-~0.0,2.6
Andorra,SouthernEurope,77,163.8,102.3,2812,39896.4,-99,-1.6,1.2

In [105]:
#Economic Freedom: Extraction
raw_file = "../Selected Data/economic_freedom_index2019_data.csv"
free_eco_df = pd.read_csv(raw_file, encoding="ISO-8859-1")
free_eco_df.head()

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
2,3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
3,4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
4,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6

In [106]:
#Economic Freedom: Transformation
free_eco_df.set_index('CountryID', inplace = True)
free_eco_df.head()

,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,Tax Burden,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
CountryID,,,,,,,,,,,,,,,,,,,,,
1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,91.7,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,86.3,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,76.4,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,83.9,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,69.3,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6

In [107]:
#Economic Freedom: Transformation

free_eco_df.columns=free_eco_df.columns.str.replace('(','')
free_eco_df.columns=free_eco_df.columns.str.replace(')','')
free_eco_df.columns=free_eco_df.columns.str.replace('%','')
free_eco_df.columns=free_eco_df.columns.str.replace(',','')
free_eco_df.columns=free_eco_df.columns.str.replace(r"[\"\',]", '')
free_eco_df.columns =free_eco_df.columns.str.rstrip()

free_eco_df = free_eco_df[free_eco_df.columns.drop('Country')]

free_eco_df.columns=free_eco_df.columns.str.replace(' ','_')
free_eco_df.columns

Index(['Country_Name', 'WEBNAME', 'Region', 'World_Rank', 'Region_Rank',
       '2019_Score', 'Property_Rights', 'Judical_Effectiveness',
       'Government_Integrity', 'Tax_Burden', 'Govt_Spending', 'Fiscal_Health',
       'Business_Freedom', 'Labor_Freedom', 'Monetary_Freedom',
       'Trade_Freedom', 'Investment_Freedom', 'Financial_Freedom',
       'Tariff_Rate', 'Income_Tax_Rate', 'Corporate_Tax_Rate',
       'Tax_Burden__of_GDP', 'Govt_Expenditure__of_GDP', 'Population_Millions',
       'GDP_Billions_PPP', 'GDP_Growth_Rate', '5_Year_GDP_Growth_Rate',
       'GDP_per_Capita_PPP', 'Unemployment', 'Inflation',
       'FDI_Inflow_Millions', 'Public_Debt__of_GDP'],
      dtype='object')

In [108]:
#Economic Freedom: Transformation

free_eco_df= free_eco_df.rename(columns={  
            'Tax Burden of GDP' :  'Tax Burdenof GDP', 
            'Public Debt  of GDP': 'Public Debtof GDP', 
            'Govt Expenditure  of GDP' :'Govt Expenditure of GDP'
            })

free_eco_df.columns

Index(['Country_Name', 'WEBNAME', 'Region', 'World_Rank', 'Region_Rank',
       '2019_Score', 'Property_Rights', 'Judical_Effectiveness',
       'Government_Integrity', 'Tax_Burden', 'Govt_Spending', 'Fiscal_Health',
       'Business_Freedom', 'Labor_Freedom', 'Monetary_Freedom',
       'Trade_Freedom', 'Investment_Freedom', 'Financial_Freedom',
       'Tariff_Rate', 'Income_Tax_Rate', 'Corporate_Tax_Rate',
       'Tax_Burden__of_GDP', 'Govt_Expenditure__of_GDP', 'Population_Millions',
       'GDP_Billions_PPP', 'GDP_Growth_Rate', '5_Year_GDP_Growth_Rate',
       'GDP_per_Capita_PPP', 'Unemployment', 'Inflation',
       'FDI_Inflow_Millions', 'Public_Debt__of_GDP'],
      dtype='object')

In [109]:
print(free_eco_df.dtypes)

Country_Name                 object
WEBNAME                      object
Region                       object
World_Rank                  float64
Region_Rank                 float64
2019_Score                  float64
Property_Rights             float64
Judical_Effectiveness       float64
Government_Integrity        float64
Tax_Burden                  float64
Govt_Spending               float64
Fiscal_Health               float64
Business_Freedom            float64
Labor_Freedom               float64
Monetary_Freedom            float64
Trade_Freedom               float64
Investment_Freedom          float64
Financial_Freedom           float64
Tariff_Rate                 float64
Income_Tax_Rate             float64
Corporate_Tax_Rate          float64
Tax_Burden__of_GDP          float64
Govt_Expenditure__of_GDP    float64
Population_Millions          object
GDP_Billions_PPP             object
GDP_Growth_Rate             float64
5_Year_GDP_Growth_Rate      float64
GDP_per_Capita_PPP           object
Unemployment                 object
Inflation                   float64
FDI_Inflow_Millions          object
Public_Debt__of_GDP         float64
dtype: object

In [137]:
#Economic Freedom: Transformation


free_eco_df2 = free_eco_df.replace('N/A',0) 
free_eco_df3 = free_eco_df2.fillna(0)
# CLEAN SEVERAL COLUMNS 
# make a list of columns that need cleaning = 'cols'
cols = ['Population_Millions', 'Unemployment', 'GDP_Billions_PPP', 'GDP_per_Capita_PPP' ,'FDI_Inflow_Millions']
# remove  $ dollars sign and commas # from 3 columns  
# this dataframe is called  ' free_eco_df3 ' 
# this is how you remove parethesis   '\( \)':  YOU MUST HAVE A SPACE BTWN BACKSLASHES !!! OR WONT WORK you cant write  ')' : '' 
free_eco_df3[cols] = free_eco_df3[cols].replace({'2009':'',  '2014':'',  '2015': '',   '2016':'',    'CHF' :'',  'ppl.' :'', 'est.' :'', '\$': '',   ',': '' }, regex=True) 
 
free_eco_df3.dtypes

Country_Name                 object
WEBNAME                      object
Region                       object
World_Rank                  float64
Region_Rank                 float64
2019_Score                  float64
Property_Rights             float64
Judical_Effectiveness       float64
Government_Integrity        float64
Tax_Burden                  float64
Govt_Spending               float64
Fiscal_Health               float64
Business_Freedom            float64
Labor_Freedom               float64
Monetary_Freedom            float64
Trade_Freedom               float64
Investment_Freedom          float64
Financial_Freedom           float64
Tariff_Rate                 float64
Income_Tax_Rate             float64
Corporate_Tax_Rate          float64
Tax_Burden__of_GDP          float64
Govt_Expenditure__of_GDP    float64
Population_Millions          object
GDP_Billions_PPP             object
GDP_Growth_Rate             float64
5_Year_GDP_Growth_Rate      float64
GDP_per_Capita_PPP           object
Unemployment                 object
Inflation                   float64
FDI_Inflow_Millions          object
Public_Debt__of_GDP         float64
dtype: object

In [111]:
free_eco_df3[cols] = free_eco_df3[cols].replace( {  '\( \)': '' }, regex=True ) 
free_eco_df3[cols] = free_eco_df3[cols].replace( {  '\(\)': '' }, regex=True )

In [112]:
free_eco_df3[cols] = free_eco_df3[cols].apply(pd.to_numeric, errors='coerce')
#run dtypes to verify converion 
free_eco_df3.dtypes

Country_Name                 object
WEBNAME                      object
Region                       object
World_Rank                  float64
Region_Rank                 float64
2019_Score                  float64
Property_Rights             float64
Judical_Effectiveness       float64
Government_Integrity        float64
Tax_Burden                  float64
Govt_Spending               float64
Fiscal_Health               float64
Business_Freedom            float64
Labor_Freedom               float64
Monetary_Freedom            float64
Trade_Freedom               float64
Investment_Freedom          float64
Financial_Freedom           float64
Tariff_Rate                 float64
Income_Tax_Rate             float64
Corporate_Tax_Rate          float64
Tax_Burden__of_GDP          float64
Govt_Expenditure__of_GDP    float64
Population_Millions         float64
GDP_Billions_PPP            float64
GDP_Growth_Rate             float64
5_Year_GDP_Growth_Rate      float64
GDP_per_Capita_PPP            int64
Unemployment                float64
Inflation                   float64
FDI_Inflow_Millions         float64
Public_Debt__of_GDP         float64
dtype: object

In [136]:
free_eco_df3.to_csv("free_eco_clean.csv", encoding="utf-8", index=True, header=True)
free_eco_df3

,Country_Name,WEBNAME,Region,World_Rank,Region_Rank,2019_Score,Property_Rights,Judical_Effectiveness,Government_Integrity,Tax_Burden,...,Govt_Expenditure__of_GDP,Population_Millions,GDP_Billions_PPP,GDP_Growth_Rate,5_Year_GDP_Growth_Rate,GDP_per_Capita_PPP,Unemployment,Inflation,FDI_Inflow_Millions,Public_Debt__of_GDP
CountryID,,,,,,,,,,,,,,,,,,,,,
1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,91.7,...,25.6,35.5,69.6,2.5,2.9,1958,8.8,5.0,53.9,7.3
2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,86.3,...,29.5,2.9,36.0,3.9,2.5,12507,13.9,2.0,1119.1,71.2
3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,76.4,...,41.4,41.5,632.9,2.0,3.1,15237,10.0,5.6,1203.0,25.8
4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,83.9,...,25.3,28.2,190.3,0.7,2.9,6753,8.2,31.7,-2254.5,65.3
5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,69.3,...,41.0,44.1,920.2,2.9,0.7,20876,8.7,25.7,11857.0,52.6
6,Armenia,Armenia,Europe,47.0,24.0,67.7,57.2,46.3,38.6,84.7,...,26.4,3.0,28.3,7.5,3.6,9456,18.2,0.9,245.7,53.5
7,Australia,Australia,Asia-Pacific,5.0,4.0,80.9,79.1,86.5,79.9,62.8,...,36.5,24.8,1246.5,2.3,2.4,50334,5.6,2.0,46368.0,41.6
8,Austria,Austria,Europe,31.0,16.0,72.0,84.2,71.3,77.4,50.5,...,50.2,8.8,439.6,2.9,1.3,49869,5.5,2.2,9629.6,78.8
9,Azerbaijan,Azerbaijan,Asia-Pacific,60.0,13.0,65.4,59.1,53.1,44.7,87.5,...,36.7,9.8,171.8,0.1,1.2,17492,5.0,13.0,2867.0,54.7
10,Bahamas,Bahamas,Americas,76.0,15.0,62.9,42.2,46.9,43.7,97.3,...,21.0,0.4,11.6,1.3,-0.7,31139,12.6,1.4,927.7,57.2
11,Bahrain,Bahrain,Middle East and North Africa,54.0,5.0,66.4,63.5,50.7,53.6,99.7,...,35.3,1.5,70.4,3.2,3.8,48505,1.2,1.4,518.9,90.3
12,Bangladesh,Bangladesh,Asia-Pacific,121.0,27.0,55.6,36.1,34.5,24.4,72.7,...,13.6,163.2,687.1,7.1,6.7,4211,4.4,5.7,2151.6,32.4
13,Barbados,Barbados,Americas,67.0,13.0,64.7,52.9,59.9,53.8,70.1,...,34.1,0.3,5.2,0.9,0.6,18664,9.7,4.4,286.2,132.9
14,Belarus,Belarus,Europe,104.0,42.0,57.9,55.2,51.7,37.7,89.4,...,44.2,9.5,178.9,2.4,-0.3,18931,0.5,6.0,1276.4,51.0
15,Belgium,Belgium,Europe,48.0,25.0,67.3,81.3,61.6,72.5,47.1,...,53.2,11.4,528.5,1.7,1.2,46553,7.4,2.2,740.4,103.2
16,Belize,Belize,Americas,123.0,24.0,55.4,41.7,46.9,27.2,79.9,...,33.7,0.4,3.2,0.8,1.8,8324,9.3,1.1,77.0,99.0
17,Benin,Benin,Sub-Saharan Africa,127.0,21.0,55.3,37.2,32.8,28.1,69.3,...,23.5,11.1,25.3,5.6,5.0,2277,2.5,0.1,184.4,54.6
18,Bhutan,Bhutan,Asia-Pacific,74.0,16.0,62.9,62.5,55.4,54.5,83.0,...,30.7,0.8,7.0,6.0,5.2,8744,2.4,3.4,10.3,102.4
19,Bolivia,Bolivia,Americas,173.0,30.0,42.3,20.5,12.3,19.7,82.4,...,41.1,11.1,83.6,4.2,5.1,7547,3.1,2.8,724.7,50.9
20,Bosnia and Herzegovina,BosniaHerzegovina,Europe,83.0,37.0,61.9,40.2,37.9,30.2,84.3,...,42.4,3.5,44.6,2.7,2.5,12724,25.6,1.3,425.2,41.0
21,Botswana,Botswana,Sub-Saharan Africa,36.0,3.0,69.5,58.1,45.7,52.4,82.7,...,33.7,2.2,38.9,2.2,4.1,17828,17.4,3.3,400.6,15.6
22,Brazil,Brazil,Americas,150.0,27.0,51.9,57.3,51.7,28.1,70.5,...,38.6,207.7,3240.3,1.0,-0.5,15603,13.3,3.4,62712.6,84.0
186,Brunei Darussalam,Brunei,Asia-Pacific,63.0,14.0,65.1,64.0,56.0,43.7,90.7,...,36.6,0.4,33.5,0.5,-1.4,78196,7.1,-0.1,-46.3,2.7
23,Bulgaria,Bulgaria,Europe,37.0,19.0,69.0,62.5,41.9,35.1,90.2,...,34.7,7.1,153.1,3.6,2.7,21687,6.2,1.2,1070.7,23.9
24,Burkina Faso,BurkinaFaso,Sub-Saharan Africa,96.0,9.0,59.4,49.1,42.9,36.6,81.9,...,25.8,18.9,35.8,6.4,5.3,1889,6.3,0.4,485.9,38.3
25,Burma,Burma,Asia-Pacific,139.0,35.0,53.6,34.7,18.1,30.6,86.6,...,22.1,52.6,328.7,6.7,7.2,6244,0.8,5.1,4341.0,34.7
26,Burundi,Burundi,Sub-Saharan Africa,162.0,39.0,48.9,20.6,31.0,26.2,74.0,...,23.6,10.9,8.0,0.0,1.1,735,1.6,16.6,0.3,56.7
27,Cambodia,Cambodia,Asia-Pacific,105.0,22.0,57.8,37.4,27.6,16.7,89.7,...,21.7,16.0,64.3,6.9,7.1,4012,0.2,2.9,2784.4,35.1
28,Cameroon,Cameroon,Sub-Saharan Africa,145.0,29.0,52.4,42.5,31.3,25.5,74.4,...,20.4,24.3,88.9,3.2,4.9,3660,4.2,0.6,672.5,33.8
29,Canada,Canada,Americas,8.0,1.0,77.7,87.0,69.4,84.6,76.8,...,40.3,36.7,1769.3,3.0,2.1,48265,6.3,1.6,24243.8,89.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Sri Lanka,SriLanka,Asia-Pacific,115.0,25.0,56.4,44.7,39.4,28.9,84.9,...,19.8,21.4,274.7,3.1,4.2,12811,4.1,6.5,1374.9,79.4
154,Sudan,Sudan,Sub-Saharan Africa,166.0,41.0,47.7,27.5,22.2,26.2,86.3,...,10.6,40.8,187.0,3.2,3.0,4586,12.7,32.4,1065.3,126.0
155,Suriname,Suriname,Americas,165.0,28.0,48.1,49.1,22.2,35.5,70.9,...,27.6,0.6,8.5,0.0,-0.9,14606,8.1,22.0,-87.3,72.1
157,Sweden,Sweden,Europe,19.0,10.0,75.2,89.5,84.0,88.0,43.2,...,49.4,10.1,520.9,2.4,2.8,51475,6.7,1.9,15395.7,40.9
158,Switzerland,Switzerland,Europe,4.0,1.0,81.9,85.3,82.0,88.0,70.5,...,34.3,8.4,517.2,1.1,1.6,61422,4.8,0.5,40986.1,42.8
159,Syria,Syria,Middle East and North Africa,0.0,0.0,0.0,37.0,24.4,20.3,0.0,...,0.0,18.4,0.0,0.0,0.0,0,14.9,0.0,0.0,0.0
160,Taiwan,Taiwan,Asia-Pacific,10.0,5.0,77.3,85.4,70.1,69.2,75.0,...,17.7,23.6,1185.5,2.8,2.2,50294,3.8,0.6,3255.0,35.2
161,Tajikistan,Tajikistan,Asia-Pacific,122.0,28.0,55.6,47.8,52.1,36.4,91.8,...,34.3,8.8,28.4,7.1,6.8,3212,10.3,7.3,141.3,47.8
162,Tanzania,Tanzania,Sub-Saharan Africa,94.0,7.0,60.2,35.4,41.4,33.2,80.5,...,18.0,50.0,162.2,6.0,6.8,3240,2.2,5.3,1180.4,38.2
163,Thailand,Thailand,Asia-Pacific,43.0,10.0,68.3,53.7,45.9,36.4,81.3,...,21.8,69.1,1233.7,3.9,2.8,17856,1.1,0.7,7635.2,41.9
164,Timor-Leste,TimorLeste,Asia-Pacific,172.0,42.0,44.2,29.7,13.1,32.1,96.3,...,57.5,1.2,6.8,-0.5,3.1,5444,3.4,0.6,6.7,0.0
165,Togo,Togo,Sub-Saharan Africa,158.0,35.0,50.3,35.5,29.6,28.1,67.8,...,27.7,7.8,12.9,4.4,5.5,1659,1.8,-0.7,145.6,78.6
166,Tonga,Tonga,Asia-Pacific,108.0,23.0,57.7,59.2,26.6,38.1,85.5,...,44.4,0.1,0.6,3.1,2.4,5608,1.1,8.0,13.8,48.0
167,Trinidad and Tobago,TrinidadTobago,Americas,112.0,22.0,57.0,52.3,40.6,32.9,82.3,...,35.7,1.4,43.0,-2.6,-1.3,31367,4.8,1.9,178.7,41.3
168,Tunisia,Tunisia,Middle East and North Africa,125.0,10.0,55.4,49.2,42.7,36.6,74.4,...,29.2,11.5,135.4,1.9,1.7,11755,15.4,5.3,879.5,71.3
169,Turkey,Turkey,Europe,68.0,33.0,64.6,55.8,49.8,41.2,76.4,...,34.1,80.8,2173.2,7.0,6.0,26893,11.3,11.1,10864.0,28.5
170,Turkmenistan,Turkmenistan,Asia-Pacific,164.0,40.0,48.4,31.6,29.8,20.3,95.9,...,16.4,5.7,103.5,6.5,7.9,18126,3.4,8.0,2313.5,28.8
171,Uganda,Uganda,Sub-Saharan Africa,95.0,8.0,59.7,42.2,38.5,25.4,73.3,...,19.4,37.7,88.7,4.5,4.3,2354,2.1,5.6,699.7,39.0
172,Ukraine,Ukraine,Europe,147.0,44.0,52.3,43.9,31.5,29.6,81.8,...,42.1,42.3,368.8,2.5,-2.3,8713,9.5,14.4,2202.0,75.6
173,United Arab Emirates,UnitedArabEmirates,Middle East and North Africa,9.0,1.0,77.6,81.8,87.1,78.8,99.2,...,32.3,10.1,686.8,0.5,3.3,67741,1.7,2.0,10354.2,19.5
174,United Kingdom,UnitedKingdom,Europe,7.0,3.0,78.9,92.3,85.9,83.8,64.7,...,41.6,66.1,2914.0,1.8,2.2,44118,4.3,2.7,15090.0,87.0
175,United States,UnitedStates,Americas,12.0,2.0,76.8,79.3,78.6,77.4,75.1,...,37.8,325.9,19390.6,2.3,2.2,59501,4.4,2.1,275381.0,107.8
176,Uruguay,Uruguay,Americas,40.0,6.0,68.6,68.3,58.9,69.2,77.2,...,32.9,3.5,78.1,3.1,2.6,22371,7.9,6.2,-124.6,66.2
177,Uzbekistan,Uzbekistan,Asia-Pacific,140.0,36.0,53.3,49.8,34.3,25.2,91.3,...,33.0,32.1,222.6,5.3,7.4,6929,7.2,12.5,95.8,24.5
178,Vanuatu,Vanuatu,Asia-Pacific,116.0,26.0,56.4,65.9,36.4,51.9,97.3,...,39.1,0.3,0.8,4.2,2.4,2739,5.2,3.1,24.7,48.4
179,Venezuela,Venezuela,Americas,179.0,32.0,25.9,7.6,13.1,7.9,74.7,...,37.4,31.4,380.7,-14.0,-7.8,12114,7.7,1087.5,-68.0,34.9
180,Vietnam,Vietnam,Asia-Pacific,128.0,30.0,55.3,49.8,40.3,34.0,79.7,...,29.4,93.6,647.4,6.8,6.2,6913,2.1,3.5,14100.0,58.2
181,Yemen,Yemen,Middle East and North Africa,0.0,0.0,0.0,19.6,22.2,20.3,0.0,...,0.0,30.0,38.6,-13.8,-16.1,1287,14.0,4.9,-269.9,141.0
182,Zambia,Zambia,Sub-Saharan Africa,138.0,27.0,53.6,45.0,35.6,32.3,72.3,...,25.8,17.2,68.9,3.6,4.0,3996,7.8,6.6,1091.2,62.2
183,Zimbabwe,Zimbabwe,Sub-Saharan Africa,175.0,45.0,40.4,29.7,24.8,15.8,62.3,...,29.2,14.9,34.0,3.0,2.6,2283,5.0,1.3,289.4,78.4

In [140]:
#World Happiness Report 2015: Extraction
WH_15="../Selected Data/WHap_2015.csv"
WH_15_df = pd.read_csv(WH_15, encoding="ISO-8859-1")
WH_15_df.dtypes

Country                           object
Region                            object
Happiness Rank                     int64
Happiness Score                  float64
Standard Error                   float64
Economy (GDP per Capita)         float64
Family                           float64
Health (Life Expectancy)         float64
Freedom                          float64
Trust (Government Corruption)    float64
Generosity                       float64
Dystopia Residual                float64
dtype: object

In [141]:
#World Happiness Report 2015: Transformation
WH_columns=['Country','Happiness Rank', 'Happiness Score']
WH_15_edit= WH_15_df[WH_columns].copy()

#World Happiness Report 2015: Column headers
WH_15_edit=WH_15_edit.rename(columns={"Country":"country",
                                      "Happiness Rank":"happiness_rank",
                                     "Happiness Score":"happiness_score"})
print(WH_15_edit.dtypes)

country             object
happiness_rank       int64
happiness_score    float64
dtype: object

In [142]:
#World Happiness Report 2016: Extraction
WH_16="../Selected Data/WHap_2016.csv"
WH_16_df = pd.read_csv(WH_16)

#World Happiness Report 2016: Filtered Dataframe

WH_16_edit= WH_16_df[WH_columns].copy()

#World Happiness Report 2016: Column headers
WH_16_edit=WH_16_edit.rename(columns={"Country":"country",
                                      "Happiness Rank":"happiness_rank",
                                     "Happiness Score":"happiness_score"})
WH_16_edit.head()

       country  happiness_rank  happiness_score
0      Denmark               1            7.526
1  Switzerland               2            7.509
2      Iceland               3            7.501
3       Norway               4            7.498
4      Finland               5            7.413

In [117]:
#World Happiness Report 2017: Extraction
WH_17="../Selected Data/WHap_2017.csv"
WH_17_df=pd.read_csv(WH_17)
WH_17_df.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

In [118]:
#World Happiness Report 2017: Filtered Dataframe
WH_17_columns=['Country', 'Happiness.Rank', 'Happiness.Score']
WH_17_edit= WH_17_df[WH_17_columns].copy()

#World Happiness Report 2017: Column headers
WH_17_edit=WH_17_edit.rename(columns={"Country":"country",
                                      "Happiness.Rank":"happiness_rank",
                                     "Happiness.Score":"happiness_score"})
WH_17_edit.head(1)

  country  happiness_rank  happiness_score
0  Norway               1            7.537

In [119]:
#Life Expectancy: Extraction
life_file='../Selected Data/Life Expectancy Data.csv'
life_exp_df=pd.read_csv(life_file)
#life_exp_df['Country'].unique()
life_exp_df.head(2)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0

In [120]:
#Life Expectancy: Transformation
life_exp_cols=['Country', 'Year', 'Life expectancy ','Population']
life_exp_edit_df=life_exp_df[life_exp_cols].copy()

life_exp_edit_df=life_exp_edit_df.rename(columns={"Country":"country",
                                                 "Year":"year",
                                                 "Status":"status",
                                                 "Life expectancy ":"life_expectancy",
                                                 "Population":"population"})

life_exp_edit_df.columns

Index(['country', 'year', 'life_expectancy', 'population'], dtype='object')

In [121]:
#United Nations: Convert Pandas to SQL
UN_data_transformed.to_sql(name='united_nations_transformed', con=engine)

In [122]:
#United Nations: Fetch all data from table
engine.execute("SELECT * FROM united_nations_transformed").fetchall()

[('Afghanistan', 'SouthernAsia', 35530, 54.4, 106.3, 20270, 623.2, '8.6', '3.2', '5.3'),
 ('Albania', 'SouthernEurope', 2930, 106.9, 101.9, 11541, 3984.2, '15.8', '-0.1', '1.7'),
 ('Algeria', 'NorthernAfrica', 41318, 17.3, 102.0, 164779, 4154.1, '11.4', '2.0', '3.0'),
 ('American Samoa', 'Polynesia', 56, 278.2, 103.6, -99, -99.0, '...', '-~0.0', '2.6'),
 ('Andorra', 'SouthernEurope', 77, 163.8, 102.3, 2812, 39896.4, '-99', '-1.6', '1.2'),
 ('Angola', 'MiddleAfrica', 29784, 23.9, 96.2, 117955, 4714.1, '6.6', '3.5', '6.0'),
 ('Anguilla', 'Caribbean', 15, 165.7, 97.6, 320, 21879.6, '...', '1.2', '...'),
 ('Antigua and Barbuda', 'Caribbean', 102, 231.8, 92.3, 1356, 14764.5, '...', '1.1', '2.1'),
 ('Argentina', 'SouthAmerica', 44271, 16.2, 95.9, 632343, 14564.5, '6.5', '1.0', '2.3'),
 ('Armenia', 'WesternAsia', 2930, 102.9, 88.8, 10529, 3489.1, '16.6', '0.3', '1.6'),
 ('Aruba', 'Caribbean', 105, 584.8, 90.4, 2702, 26005.4, '...', '0.5', '1.8'),
 ('Australia', 'Oceania', 24451, 3.2, 99.3, 1230859, 51352.2, '5.5', '1.5', '1.9'),
 ('Austria', 'WesternEurope', 8736, 106.0, 96.2, 376967, 44117.7, '6.2', '0.6', '1.4'),
 ('Azerbaijan', 'WesternAsia', 9828, 118.9, 99.3, 53049, 5438.7, '5.2', '1.3', '2.1'),
 ('Bahamas', 'Caribbean', 395, 39.5, 95.9, 8854, 22817.2, '14.7', '1.4', '1.8'),
 ('Bahrain', 'WesternAsia', 1493, 1963.9, 168.3, 31126, 22600.2, '1.3', '2.0', '2.1'),
 ('Bangladesh', 'SouthernAsia', 164670, 1265.0, 101.7, 194466, 1207.9, '4.0', '1.2', '2.2'),
 ('Barbados', 'Caribbean', 286, 664.5, 91.9, 4385, 15429.4, '11.3', '0.3', '1.8'),
 ('Belarus', 'EasternEurope', 9468, 46.7, 87.0, 54609, 5750.8, '0.5', '~0.0', '1.6'),
 ('Belgium', 'WesternEurope', 11429, 377.5, 97.3, 455107, 40277.8, '8.3', '0.6', '1.8'),
 ('Belize', 'CentralAmerica', 375, 16.4, 99.2, 1721, 4789.4, '11.5', '2.2', '2.6'),
 ('Benin', 'WesternAfrica', 11176, 99.1, 99.5, 8476, 779.1, '1.0', '2.8', '5.2'),
 ('Bermuda', 'NorthernAmerica', 61, 1227.0, 91.4, 5853, 94399.9, '6.7', '-0.6', '1.5'),
 ('Bhutan', 'SouthernAsia', 808, 21.2, 113.1, 2074, 2677.1, '2.4', '1.6', '2.2'),
 ('Bolivia (Plurinational State of)', 'SouthAmerica', 11052, 10.2, 100.2, 32998, 3076.8, '3.8', '1.6', '3.0'),
 ('Bonaire, Sint Eustatius and Saba', 'Caribbean', 25, 77.4, -99.0, -99, -99.0, '-99', '3.2', '-99'),
 ('Bosnia and Herzegovina', 'SouthernEurope', 3507, 68.8, 96.4, 16251, 4265.0, '25.4', '-1.0', '1.3'),
 ('Botswana', 'SouthernAfrica', 2292, 4.0, 97.7, 14391, 6360.6, '18.6', '1.8', '2.9'),
 ('Brazil', 'SouthAmerica', 209288, 25.0, 96.6, 1772591, 8528.3, '12.4', '0.9', '1.8'),
 ('British Virgin Islands', 'Caribbean', 31, 208.0, 97.1, 908, 30144.5, '-99', '2.0', '...'),
 ('Brunei Darussalam', 'South-easternAsia', 429, 81.3, 106.0, 12930, 30552.7, '2.1', '1.4', '1.9'),
 ('Bulgaria', 'EasternEurope', 7085, 65.3, 94.6, 48953, 6846.8, '8.1', '-0.6', '1.5'),
 ('Burkina Faso', 'WesternAfrica', 19193, 70.2, 99.5, 11065, 611.1, '2.9', '3.0', '5.6'),
 ('Burundi', 'EasternAfrica', 10864, 423.1, 96.9, 2735, 244.6, '1.7', '3.0', '6.0'),
 ('Cabo Verde', 'WesternAfrica', 546, 135.6, 99.3, 1603, 3080.2, '10.5', '1.2', '2.5'),
 ('Cambodia', 'South-easternAsia', 16005, 90.7, 95.3, 18050, 1158.7, '0.3', '1.6', '2.7'),
 ('Cameroon', 'MiddleAfrica', 24054, 50.9, 100.2, 28416, 1217.3, '4.6', '2.7', '5.0'),
 ('Canada', 'NorthernAmerica', 36624, 4.0, 98.5, 1552808, 43205.6, '7.1', '1.0', '1.6'),
 ('Cayman Islands', 'Caribbean', 62, 256.5, 100.4, 3726, 62132.0, '6.3', '1.5', '...'),
 ('Central African Republic', 'MiddleAfrica', 4659, 7.5, 97.3, 1633, 333.2, '6.9', '0.4', '5.1'),
 ('Chad', 'MiddleAfrica', 14900, 11.8, 100.2, 10009, 713.0, '5.8', '3.3', '6.3'),
 ('Channel Islands', 'NorthernEurope', 165, 870.1, 98.4, -99, -99.0, '8.7', '0.5', '1.5'),
 ('Chile', 'SouthAmerica', 18055, 24.3, 98.2, 240796, 13416.2, '6.8', '0.9', '1.8'),
 ('China, Hong Kong SAR', 'EasternAsia', 7365, 7014.2, 85.1, 309236, 42431.0, '3.5', '0.6', '1.2'),
 ('China, Macao SAR', 'EasternAsia', 623, 20821.6, 92.3, 46178, 78586.4, '3.2', '2.3', '1.2'),
 ('China', 'EasternAsia', 1409517, 150.1, 106.3, 11158457, 8109.1, '4.6', '0.5', '1.6'),
 ('Colombia', 'SouthAmerica', 49066, 44.2, 96.8, 292080, 6056.1, '10.5', '1.0', '1.9'),
 ('Comoros', 'EasternAfrica', 814, 437.4, 101.8, 1079, 1368.9, '20.0', '2.4', '4.6'),
 ('Congo', 'MiddleAfrica', 5261, 15.4, 100.1, 8493, 1838.1, '11.5', '2.6', '4.9'),
 ('Cook Islands', 'Polynesia', 17, 72.4, 97.4, 294, 14118.7, '8.2', '-1.2', '2.6'),
 ('Costa Rica', 'CentralAmerica', 4906, 96.1, 100.1, 52958, 11015.0, '8.6', '1.1', '1.9'),
 ('Croatia', 'SouthernEurope', 4189, 74.9, 93.1, 48676, 11479.4, '11.7', '-0.4', '1.5'),
 ('Cuba', 'Caribbean', 11485, 107.9, 100.1, 87206, 7656.6, '3.0', '0.2', '1.7'),
 ('Cyprus', 'WesternAsia', 1180, 127.7, 100.2, 19561, 21941.9, '10.3', '0.9', '1.4'),
 ('Czechia', 'EasternEurope', 10618, 137.5, 96.7, 185156, 17561.7, '3.9', '0.1', '1.5'),
 ("Democratic People's Republic of Korea", 'EasternAsia', 25491, 211.7, 95.7, 16283, 648.0, '4.3', '0.5', '2.0'),
 ('Democratic Republic of the Congo', 'MiddleAfrica', 81340, 35.9, 99.6, 37569, 486.2, '3.6', '3.3', '6.4'),
 ('Denmark', 'NorthernEurope', 5734, 135.1, 99.0, 301308, 53149.3, '6.0', '0.5', '1.7'),
 ('Djibouti', 'EasternAfrica', 957, 41.3, 100.7, 1737, 1956.3, '6.6', '1.7', '3.1'),
 ('Dominica', 'Caribbean', 74, 98.6, 103.0, 512, 7051.1, '...', '0.5', '...'),
 ('Dominican Republic', 'Caribbean', 10767, 222.8, 99.2, 67103, 6373.6, '14.4', '1.2', '2.5'),
 ('Ecuador', 'SouthAmerica', 16625, 66.9, 99.9, 100177, 6205.1, '5.8', '1.6', '2.6'),
 ('Egypt', 'NorthernAfrica', 97553, 98.0, 102.3, 315917, 3452.3, '11.5', '2.2', '3.4'),
 ('El Salvador', 'CentralAmerica', 6378, 307.8, 88.5, 25850, 4219.4, '6.4', '0.5', '2.2'),
 ('Equatorial Guinea', 'MiddleAfrica', 1268, 45.2, 124.0, 13812, 16344.1, '7.7', '4.2', '5.0'),
 ('Eritrea', 'EasternAfrica', 5069, 50.2, 100.4, 4783, 914.9, '7.3', '2.0', '4.4'),
 ('Estonia', 'NorthernEurope', 1310, 30.9, 88.2, 22460, 17112.0, '7.2', '-0.3', '1.6'),
 ('Ethiopia', 'EasternAfrica', 104957, 105.0, 99.7, 59917, 602.8, '5.7', '2.6', '4.6'),
 ('Falkland Islands (Malvinas)', 'SouthAmerica', 3, 0.2, 110.5, -99, -99.0, '1.2', '0.3', '-99'),
 ('Faroe Islands', 'NorthernEurope', 49, 35.3, 107.2, -99, -99.0, '4.0', '0.2', '2.4'),
 ('Fiji', 'Melanesia', 906, 49.6, 103.1, 4391, 4921.9, '7.7', '0.7', '2.6'),
 ('Finland', 'NorthernEurope', 5523, 18.2, 97.2, 231960, 42148.1, '8.9', '0.4', '1.8'),
 ('France', 'WesternEurope', 64980, 118.7, 96.7, 2418946, 36304.2, '9.8', '0.4', '2.0'),
 ('French Guiana', 'SouthAmerica', 283, 3.4, 100.0, -99, -99.0, '21.3', '2.8', '3.5'),
 ('French Polynesia', 'Polynesia', 283, 77.3, 103.7, 5135, 18161.0, '17.0', '0.7', '2.1'),
 ('Gabon', 'MiddleAfrica', 2025, 7.9, 105.6, 13735, 7960.7, '18.1', '3.3', '4.0'),
 ('Gambia', 'WesternAfrica', 2101, 207.6, 98.0, 942, 473.2, '29.7', '3.1', '5.6'),
 ('Georgia', 'WesternAsia', 3912, 56.3, 91.4, 13965, 3491.4, '11.4', '-1.4', '2.0'),
 ('Germany', 'WesternEurope', 82114, 235.6, 97.0, 3363600, 41686.2, '4.2', '0.2', '1.4'),
 ('Ghana', 'WesternAfrica', 28834, 126.7, 99.3, 37156, 1355.6, '5.9', '2.4', '4.2'),
 ('Gibraltar', 'SouthernEurope', 35, 3457.1, 101.8, -99, -99.0, '-99', '0.6', '-99'),
 ('Greece', 'SouthernEurope', 11160, 86.6, 96.9, 194860, 17788.0, '23.0', '-0.4', '1.3'),
 ('Greenland', 'NorthernAmerica', 56, 0.1, 112.1, 2078, 36976.7, '9.7', '-0.1', '2.0'),
 ('Grenada', 'Caribbean', 108, 317.1, 100.9, 954, 8933.8, '...', '0.4', '2.2'),
 ('Guadeloupe', 'Caribbean', 450, 266.0, 86.4, -99, -99.0, '26.1', '-~0.0', '2.0'),
 ('Guam', 'Micronesia', 164, 304.1, 102.6, -99, -99.0, '10.7', '0.3', '2.4'),
 ('Guatemala', 'CentralAmerica', 16914, 157.8, 96.9, 63794, 3903.5, '2.4', '2.1', '3.2'),
 ('Guinea-Bissau', 'WesternAfrica', 1861, 66.2, 96.9, 978, 530.0, '6.5', '2.6', '4.9'),
 ('Guinea', 'WesternAfrica', 12717, 51.8, 100.6, 8875, 703.9, '6.8', '2.3', '5.1'),
 ('Guyana', 'SouthAmerica', 778, 4.0, 101.9, 3282, 4278.8, '11.3', '0.6', '2.6'),
 ('Haiti', 'Caribbean', 10981, 398.4, 97.8, 8501, 793.7, '12.9', '1.4', '3.1'),
 ('Holy See', 'SouthernEurope', 1, 1800.0, 219.2, -99, -99.0, '-99', '~0.0', '-99'),
 ('Honduras', 'CentralAmerica', 9265, 82.8, 99.4, 20365, 2521.9, '5.6', '1.8', '2.6'),
 ('Hungary', 'EasternEurope', 9722, 107.4, 90.7, 121715, 12350.6, '4.5', '-0.3', '1.3'),
 ('Iceland', 'NorthernEurope', 335, 3.3, 100.7, 16780, 50936.0, '3.6', '0.6', '2.0'),
 ('India', 'SouthernAsia', 1339180, 450.4, 107.6, 2116239, 1614.2, '3.4', '1.2', '2.4'),
 ('Indonesia', 'South-easternAsia', 263991, 145.7, 101.4, 861934, 3346.5, '5.8', '1.2', '2.4'),
 ('Iran (Islamic Republic of)', 'SouthernAsia', 81163, 49.8, 101.2, 398563, 5038.1, '11.3', '1.2', '1.7'),
 ('Iraq', 'WesternAsia', 38275, 88.1, 102.5, 164234, 4509.0, '16.1', '3.2', '4.6'),
 ('Ireland', 'NorthernEurope', 4762, 69.1, 98.4, 283716, 60513.6, '7.6', '0.3', '2.0'),
 ('Isle of Man', 'NorthernEurope', 84, 147.9, 98.2, -99, -99.0, '2.6', '0.8', '-99'),
 ('Israel', 'WesternAsia', 8322, 384.5, 98.7, 299413, 37129.4, '5.9', '1.6', '3.0'),
 ('Italy', 'SouthernEurope', 59360, 201.8, 95.1, 1821580, 30462.4, '11.4', '-0.1', '1.4'),
 ('Jamaica', 'Caribbean', 2890, 266.9, 99.0, 14262, 5105.8, '13.1', '0.4', '2.1'),
 ('Japan', 'EasternAsia', 127484, 349.7, 95.4, 4383076, 34628.7, '3.0', '-0.1', '1.4'),
 ('Jordan', 'WesternAsia', 9702, 109.3, 102.6, 37517, 4940.1, '13.4', '4.9', '3.6'),
 ('Kazakhstan', 'CentralAsia', 18204, 6.7, 93.9, 181754, 10312.1, '5.6', '1.6', '2.7'),
 ('Kenya', 'EasternAfrica', 49700, 87.3, 98.8, 63399, 1376.7, '10.8', '2.7', '4.1'),
 ('Kiribati', 'Micronesia', 116, 143.7, 97.3, 162, 1442.9, '...', '1.8', '3.8'),
 ('Kuwait', 'WesternAsia', 4136, 232.1, 134.9, 114054, 29303.9, '2.2', '5.4', '2.0'),
 ('Kyrgyzstan', 'CentralAsia', 6045, 31.5, 98.4, 6572, 1106.4, '7.7', '1.6', '3.1'),
 ("Lao People's Democratic Republic", 'South-easternAsia', 6858, 29.7, 99.5, 12585, 1850.2, '1.5', '1.3', '2.9'),
 ('Latvia', 'NorthernEurope', 1950, 31.3, 84.9, 27004, 13704.1, '9.6', '-1.2', '1.5'),
 ('Lebanon', 'WesternAsia', 6082, 594.6, 100.6, 50149, 8571.4, '7.0', '6.0', '1.7'),
 ('Lesotho', 'SouthernAfrica', 2233, 73.6, 94.4, 2008, 940.6, '27.5', '1.3', '3.3'),
 ('Liberia', 'WesternAfrica', 4732, 49.1, 101.8, 2053, 455.9, '4.1', '2.6', '4.8'),
 ('Libya', 'NorthernAfrica', 6375, 3.6, 101.7, 34457, 5488.2, '19.2', '0.2', '2.4'),
 ('Liechtenstein', 'WesternEurope', 38, 237.0, 98.4, 6361, 169491.8, '2.6', '0.8', '1.5'),
 ('Lithuania', 'NorthernEurope', 2890, 46.1, 85.4, 41402, 14383.7, '9.2', '-1.3', '1.6'),
 ('Luxembourg', 'WesternEurope', 584, 225.3, 101.0, 56802, 100160.8, '5.6', '2.2', '1.5'),
 ('Madagascar', 'EasternAfrica', 25571, 44.0, 99.5, 9739, 401.8, '2.3', '2.7', '4.4'),
 ('Malawi', 'EasternAfrica', 18622, 197.5, 98.2, 6420, 372.9, '6.8', '2.9', '4.9'),
 ('Malaysia', 'South-easternAsia', 31624, 96.3, 106.7, 296284, 9768.4, '3.3', '1.8', '2.1'),
 ('Maldives', 'SouthernAsia', 436, 1454.4, 131.8, 3435, 9446.5, '2.9', '2.8', '2.2'),
 ('Mali', 'WesternAfrica', 18542, 15.2, 100.2, 13100, 744.3, '8.1', '2.9', '6.4'),
 ('Malta', 'SouthernEurope', 431, 1346.4, 100.9, 9747, 23280.7, '5.4', '0.5', '1.4'),
 ('Marshall Islands', 'Micronesia', 53, 295.2, 104.5, 183, 3452.6, '4.7', '0.2', '4.1'),
 ('Martinique', 'Caribbean', 385, 363.1, 83.5, -99, -99.0, '22.8', '-0.5', '2.0'),
 ('Mauritania', 'WesternAfrica', 4420, 4.3, 101.6, 5023, 1235.0, '12.0', '2.9', '4.9'),
 ('Mauritius', 'EasternAfrica', 1265, 623.2, 97.9, 11511, 9040.9, '7.6', '0.2', '1.5'),
 ('Mayotte', 'EasternAfrica', 253, 674.8, 96.7, -99, -99.0, '-99', '2.8', '4.1'),
 ('Mexico', 'CentralAmerica', 129163, 66.4, 99.2, 1140724, 8980.9, '4.1', '1.4', '2.3'),
 ('Micronesia (Federated States of)', 'Micronesia', 106, 150.8, 105.1, 315, 3015.2, '-99', '0.2', '3.3'),
 ('Monaco', 'WesternEurope', 39, 25969.8, 94.7, 6258, 165870.6, '...', '0.6', '-99'),
 ('Mongolia', 'EasternAsia', 3076, 2.0, 97.9, 11758, 3973.4, '6.3', '1.9', '2.8'),
 ('Montenegro', 'SouthernEurope', 629, 46.8, 97.4, 4020, 6424.1, '17.4', '0.1', '1.7'),
 ('Montserrat', 'Caribbean', 5, 51.8, 106.0, 59, 11553.4, '5.6', '0.7', '...'),
 ('Morocco', 'NorthernAfrica', 35740, 80.1, 98.1, 100359, 2919.3, '10.4', '1.4', '2.6'),
 ('Mozambique', 'EasternAfrica', 29669, 37.7, 95.5, 14806, 529.2, '24.1', '2.9', '5.4'),
 ('Myanmar', 'South-easternAsia', 53371, 81.7, 95.5, 62601, 1161.5, '0.8', '0.9', '2.3'),
 ('Namibia', 'SouthernAfrica', 2534, 3.1, 94.7, 11491, 4673.6, '24.9', '2.2', '3.6'),
 ('Nauru', 'Micronesia', 11, 568.0, 101.9, 189, 18469.2, '23.0', '2.3', '3.9'),
 ('Nepal', 'SouthernAsia', 29305, 204.4, 94.3, 20658, 724.5, '3.0', '1.2', '2.3'),
 ('Netherlands', 'WesternEurope', 17036, 505.2, 99.0, 750318, 44332.1, '5.6', '0.3', '1.7'),
 ('New Caledonia', 'Melanesia', 276, 15.1, 101.5, 8937, 33965.7, '15.1', '1.4', '2.2'),
 ('New Zealand', 'Oceania', 4706, 17.9, 96.7, 173417, 38294.3, '5.5', '1.1', '2.0'),
 ('Nicaragua', 'CentralAmerica', 6218, 51.7, 97.2, 12693, 2086.9, '6.1', '1.2', '2.3'),
 ('Niger', 'WesternAfrica', 21477, 17.0, 100.6, 7143, 359.0, '2.7', '3.8', '7.4'),
 ('Nigeria', 'WesternAfrica', 190886, 209.6, 102.7, 494583, 2714.5, '5.4', '2.7', '5.7'),
 ('Niue', 'Polynesia', 2, 6.2, 100.0, -99, -99.0, '...', '-0.1', '2.6'),
 ('Northern Mariana Islands', 'Micronesia', 55, 119.9, 107.1, -99, -99.0, '...', '0.1', '1.6'),
 ('Norway', 'NorthernEurope', 5305, 14.5, 101.8, 386578, 74185.5, '5.1', '1.2', '1.8'),
 ('Oman', 'WesternAsia', 4636, 15.0, 192.8, 69832, 15550.8, '17.8', '6.5', '2.9'),
 ('Pakistan', 'SouthernAsia', 197016, 255.6, 105.6, 266458, 1410.4, '5.9', '2.1', '3.7'),
 ('Palau', 'Micronesia', 22, 47.2, 113.3, 258, 12122.5, '...', '0.8', '2.2'),
 ('Panama', 'CentralAmerica', 4099, 55.1, 100.4, 52132, 13268.1, '6.2', '1.7', '2.6'),
 ('Papua New Guinea', 'Melanesia', 8251, 18.2, 103.5, 21315, 2797.6, '2.5', '2.2', '3.8'),
 ('Paraguay', 'SouthAmerica', 6811, 17.1, 102.9, 27714, 4174.4, '5.5', '1.3', '2.6'),
 ('Peru', 'SouthAmerica', 32166, 25.1, 99.8, 190428, 6069.1, '5.3', '1.3', '2.5'),
 ('Philippines', 'South-easternAsia', 104918, 351.9, 101.3, 292449, 2904.2, '5.9', '1.6', '3.0'),
 ('Poland', 'EasternEurope', 38171, 124.6, 93.4, 477066, 12355.5, '5.3', '-~0.0', '1.3'),
 ('Portugal', 'SouthernEurope', 10330, 112.8, 89.8, 199122, 19239.2, '10.5', '-0.4', '1.3'),
 ('Puerto Rico', 'Caribbean', 3663, 413.0, 92.6, 102906, 27939.0, '12.8', '-0.2', '1.5'),
 ('Qatar', 'WesternAsia', 2639, 227.3, 301.2, 164641, 73653.4, '0.3', '6.6', '2.0'),
 ('Republic of Korea', 'EasternAsia', 50982, 524.3, 100.2, 1377873, 27396.7, '3.6', '0.4', '1.2'),
 ('Republic of Moldova', 'EasternEurope', 4051, 123.3, 92.2, 6475, 1591.4, '5.0', '-0.1', '1.3'),
 ('Romania', 'EasternEurope', 19679, 85.5, 94.0, 177956, 9120.7, '7.1', '-0.6', '1.5'),
 ('Russian Federation', 'EasternEurope', 143990, 8.8, 86.8, 1326016, 9243.3, '5.8', '0.1', '1.7'),
 ('Rwanda', 'EasternAfrica', 12208, 494.9, 96.2, 8096, 697.3, '2.4', '2.5', '4.2'),
 ('Saint Helena', 'WesternAfrica', 4, 10.4, -99.0, -99, -99.0, '...', '-0.7', '-99'),
 ('Saint Kitts and Nevis', 'Caribbean', 55, 212.9, 97.0, 876, 15771.9, '...', '1.1', '-99'),
 ('Saint Lucia', 'Caribbean', 179, 293.2, 95.9, 1450, 7839.4, '19.0', '0.5', '1.5'),
 ('Saint Pierre and Miquelon', 'NorthernAmerica', 6, 27.5, 98.2, -99, -99.0, '-99', '~0.0', '-99'),
 ('Saint Vincent and the Grenadines', 'Caribbean', 110, 281.8, 101.7, 738, 6739.2, '19.1', '~0.0', '2.0'),
 ('Samoa', 'Polynesia', 196, 69.4, 106.6, 774, 4006.0, '6.5', '0.8', '4.2'),
 ('San Marino', 'SouthernEurope', 33, 556.7, 94.9, 1565, 49240.2, '6.6', '1.2', '...'),
 ('Sao Tome and Principe', 'MiddleAfrica', 204, 212.8, 99.2, 334, 1752.8, '13.6', '2.2', '4.7'),
 ('Saudi Arabia', 'WesternAsia', 32938, 15.3, 132.9, 653219, 20710.6, '5.5', '2.8', '2.7'),
 ('Senegal', 'WesternAfrica', 15851, 82.3, 96.6, 13633, 901.1, '9.3', '3.0', '5.0'),
 ('Serbia', 'SouthernEurope', 8791, 100.5, 95.6, 37160, 5238.6, '15.5', '-0.4', '1.6'),
 ('Seychelles', 'EasternAfrica', 95, 206.0, 97.2, 1363, 14133.2, '4.1', '0.5', '2.4'),
 ('Sierra Leone', 'WesternAfrica', 7557, 104.7, 98.1, 4483, 694.8, '3.1', '2.3', '4.8'),
 ('Singapore', 'South-easternAsia', 5709, 8155.5, 97.7, 292734, 52239.0, '2.0', '1.7', '1.2'),
 ('Sint Maarten (Dutch part)', 'Caribbean', 40, 1180.0, 95.7, 1094, 28241.7, '-99', '3.1', '-99'),
 ('Slovakia', 'EasternEurope', 5448, 113.3, 94.6, 87268, 16082.5, '9.9', '0.1', '1.4'),
 ('Slovenia', 'SouthernEurope', 2080, 103.3, 98.6, 42777, 20689.8, '8.1', '0.3', '1.6'),
 ('Solomon Islands', 'Melanesia', 611, 21.8, 103.4, 1075, 1841.6, '31.4', '2.1', '4.1'),
 ('Somalia', 'EasternAfrica', 14742, 23.5, 99.3, 1559, 144.5, '6.6', '2.9', '6.6'),
 ('South Africa', 'SouthernAfrica', 56717, 46.8, 96.4, 314571, 5773.0, '26.0', '1.4', '2.6'),
 ('South Sudan', 'EasternAfrica', 12576, 20.6, 100.4, 13167, 1067.0, '...', '3.3', '5.2'),
 ('Spain', 'SouthernEurope', 46354, 92.9, 96.2, 1192955, 25865.4, '18.3', '-0.2', '1.3'),
 ('Sri Lanka', 'SouthernAsia', 20877, 332.9, 92.5, 82316, 3973.7, '5.2', '0.5', '2.1'),
 ('State of Palestine', 'WesternAsia', 4921, 817.4, 102.9, 12677, 2715.5, '24.2', '2.7', '4.2'),
 ('Sudan', 'NorthernAfrica', 40533, 23.0, 99.9, 79546, 1977.0, '13.4', '2.3', '4.8'),
 ('Suriname', 'SouthAmerica', 563, 3.6, 100.7, 4879, 8985.3, '9.9', '1.0', '2.5'),
 ('Swaziland', 'SouthernAfrica', 1367, 79.5, 93.9, 4133, 3211.7, '25.1', '1.8', '3.3'),
 ('Sweden', 'NorthernEurope', 9911, 24.2, 100.2, 495694, 50687.5, '7.3', '0.8', '1.9'),
 ('Switzerland', 'WesternEurope', 8476, 214.5, 98.2, 670790, 80831.1, '4.6', '1.2', '1.5'),
 ('Syrian Arab Republic', 'WesternAsia', 18270, 99.5, 102.1, 28393, 1534.5, '13.8', '-2.3', '3.1'),
 ('Tajikistan', 'CentralAsia', 8921, 63.7, 100.9, 7853, 925.9, '10.8', '2.2', '3.5'),
 ('Thailand', 'South-easternAsia', 69038, 135.1, 95.2, 395168, 5814.8, '0.6', '0.4', '1.5'),
 ('The former Yugoslav Republic of Macedonia', 'SouthernEurope', 2083, 82.6, 100.0, 10052, 4836.1, '27.3', '0.1', '1.5'),
 ('Timor-Leste', 'South-easternAsia', 1296, 87.2, 103.2, 2873, 2425.4, '4.3', '2.2', '5.9'),
 ('Togo', 'WesternAfrica', 7798, 143.4, 99.4, 4086, 559.4, '6.8', '2.6', '4.7'),
 ('Tokelau', 'Polynesia', 1, 130.0, 100.0, -99, -99.0, '-99', '1.9', '2.1'),
 ('Tonga', 'Polynesia', 108, 150.0, 100.7, 402, 3784.5, '4.8', '0.4', '3.8'),
 ('Trinidad and Tobago', 'Caribbean', 1369, 266.9, 97.1, 25927, 19062.9, '4.2', '0.5', '1.8'),
 ('Tunisia', 'NorthernAfrica', 11532, 74.2, 97.6, 41199, 3660.9, '14.6', '1.2', '2.3'),
 ('Turkey', 'WesternAsia', 80745, 104.9, 97.0, 717888, 9125.8, '10.8', '1.6', '2.1'),
 ('Turkmenistan', 'CentralAsia', 5758, 12.3, 97.0, 37597, 6996.7, '8.6', '1.8', '3.0'),
 ('Turks and Caicos Islands', 'Caribbean', 35, 37.3, 104.1, 863, 25121.8, '...', '2.0', '-99'),
 ('Tuvalu', 'Polynesia', 11, 373.1, 102.0, 33, 3362.4, '...', '0.9', '3.6'),
 ('Uganda', 'EasternAfrica', 42863, 214.5, 99.0, 25282, 647.7, '2.4', '3.4', '5.9'),
 ('Ukraine', 'EasternEurope', 44223, 76.3, 86.0, 90615, 2021.6, '8.8', '-0.5', '1.5'),
 ('United Arab Emirates', 'WesternAsia', 9400, 112.4, 262.4, 370296, 40438.8, '3.7', '2.0', '1.8'),
 ('United Kingdom', 'NorthernEurope', 66182, 273.6, 97.4, 2858003, 44162.4, '5.0', '0.6', '1.9'),
 ('United Republic of Tanzania', 'EasternAfrica', 57310, 64.7, 97.8, 45628, 877.3, '2.7', '3.1', '5.2'),
 ('United States of America', 'NorthernAmerica', 324460, 35.5, 98.0, 18036648, 56053.8, '4.9', '0.7', '1.9'),
 ('United States Virgin Islands', 'Caribbean', 105, 299.7, 91.1, -99, -99.0, '9.0', '-0.2', '2.3'),
 ('Uruguay', 'SouthAmerica', 3457, 19.8, 93.5, 53442, 15573.8, '8.8', '0.3', '2.0'),
 ('Uzbekistan', 'CentralAsia', 31911, 75.0, 99.4, 69004, 2308.3, '8.9', '1.6', '2.4'),
 ('Vanuatu', 'Melanesia', 276, 22.7, 102.4, 737, 2783.0, '5.3', '2.3', '3.4'),
 ('Venezuela (Bolivarian Republic of)', 'SouthAmerica', 31977, 36.3, 99.0, 344331, 11068.9, '6.6', '1.4', '2.4'),
 ('Viet Nam', 'South-easternAsia', 95541, 308.1, 98.0, 193241, 2067.9, '2.2', '1.1', '2.0'),

In [123]:
#Life Expectancy: Convert Pandas to SQL
life_exp_edit_df.to_sql(name='life_expectancy', con=engine)

ValueError: Table 'life_expectancy' already exists.

In [124]:
#Life Expectancy: Fetch all data from table
engine.execute("SELECT * FROM life_expectancy").fetchall()

[(0, 'Afghanistan', 2015, 65.0, 33736494.0),
 (1, 'Afghanistan', 2014, 59.9, 327582.0),
 (2, 'Afghanistan', 2013, 59.9, 31731688.0),
 (3, 'Afghanistan', 2012, 59.5, 3696958.0),
 (4, 'Afghanistan', 2011, 59.2, 2978599.0),
 (5, 'Afghanistan', 2010, 58.8, 2883167.0),
 (6, 'Afghanistan', 2009, 58.6, 284331.0),
 (7, 'Afghanistan', 2008, 58.1, 2729431.0),
 (8, 'Afghanistan', 2007, 57.5, 26616792.0),
 (9, 'Afghanistan', 2006, 57.3, 2589345.0),
 (10, 'Afghanistan', 2005, 57.3, 257798.0),
 (11, 'Afghanistan', 2004, 57.0, 24118979.0),
 (12, 'Afghanistan', 2003, 56.7, 2364851.0),
 (13, 'Afghanistan', 2002, 56.2, 21979923.0),
 (14, 'Afghanistan', 2001, 55.3, 2966463.0),
 (15, 'Afghanistan', 2000, 54.8, 293756.0),
 (16, 'Albania', 2015, 77.8, 28873.0),
 (17, 'Albania', 2014, 77.5, 288914.0),
 (18, 'Albania', 2013, 77.2, 289592.0),
 (19, 'Albania', 2012, 76.9, 2941.0),
 (20, 'Albania', 2011, 76.6, 295195.0),
 (21, 'Albania', 2010, 76.2, 291321.0),
 (22, 'Albania', 2009, 76.1, 2927519.0),
 (23, 'Albania', 2008, 75.3, 2947314.0),
 (24, 'Albania', 2007, 75.9, 29717.0),
 (25, 'Albania', 2006, 74.2, 2992547.0),
 (26, 'Albania', 2005, 73.5, 311487.0),
 (27, 'Albania', 2004, 73.0, 326939.0),
 (28, 'Albania', 2003, 72.8, 339616.0),
 (29, 'Albania', 2002, 73.3, 3511.0),
 (30, 'Albania', 2001, 73.6, 36173.0),
 (31, 'Albania', 2000, 72.6, 38927.0),
 (32, 'Algeria', 2015, 75.6, 39871528.0),
 (33, 'Algeria', 2014, 75.4, 39113313.0),
 (34, 'Algeria', 2013, 75.3, 38338562.0),
 (35, 'Algeria', 2012, 75.1, 37565847.0),
 (36, 'Algeria', 2011, 74.9, 36819558.0),
 (37, 'Algeria', 2010, 74.7, 36117637.0),
 (38, 'Algeria', 2009, 74.4, 3546576.0),
 (39, 'Algeria', 2008, 74.1, 3486715.0),
 (40, 'Algeria', 2007, 73.8, 34376.0),
 (41, 'Algeria', 2006, 73.4, 33777915.0),
 (42, 'Algeria', 2005, 72.9, 33288437.0),
 (43, 'Algeria', 2004, 72.3, 3283196.0),
 (44, 'Algeria', 2003, 71.7, 3243514.0),
 (45, 'Algeria', 2002, 71.6, 3199546.0),
 (46, 'Algeria', 2001, 71.4, 31592153.0),
 (47, 'Algeria', 2000, 71.3, 3118366.0),
 (48, 'Angola', 2015, 52.4, 2785935.0),
 (49, 'Angola', 2014, 51.7, 2692466.0),
 (50, 'Angola', 2013, 51.1, 2599834.0),
 (51, 'Angola', 2012, 56.0, 259615.0),
 (52, 'Angola', 2011, 51.0, 24218565.0),
 (53, 'Angola', 2010, 49.6, 23369131.0),
 (54, 'Angola', 2009, 49.1, 22549547.0),
 (55, 'Angola', 2008, 48.7, 2175942.0),
 (56, 'Angola', 2007, 48.2, 2997687.0),
 (57, 'Angola', 2006, 47.7, 2262399.0),
 (58, 'Angola', 2005, 47.4, 19552542.0),
 (59, 'Angola', 2004, 47.1, 18865716.0),
 (60, 'Angola', 2003, 46.8, 1823369.0),
 (61, 'Angola', 2002, 46.5, 17572649.0),
 (62, 'Angola', 2001, 45.7, 16983266.0),
 (63, 'Angola', 2000, 45.3, 1644924.0),
 (64, 'Antigua and Barbuda', 2015, 76.4, None),
 (65, 'Antigua and Barbuda', 2014, 76.2, None),
 (66, 'Antigua and Barbuda', 2013, 76.1, None),
 (67, 'Antigua and Barbuda', 2012, 75.9, None),
 (68, 'Antigua and Barbuda', 2011, 75.7, None),
 (69, 'Antigua and Barbuda', 2010, 75.6, None),
 (70, 'Antigua and Barbuda', 2009, 75.4, None),
 (71, 'Antigua and Barbuda', 2008, 75.2, None),
 (72, 'Antigua and Barbuda', 2007, 75.0, None),
 (73, 'Antigua and Barbuda', 2006, 74.8, None),
 (74, 'Antigua and Barbuda', 2005, 74.6, None),
 (75, 'Antigua and Barbuda', 2004, 74.4, None),
 (76, 'Antigua and Barbuda', 2003, 74.2, None),
 (77, 'Antigua and Barbuda', 2002, 74.0, None),
 (78, 'Antigua and Barbuda', 2001, 73.8, None),
 (79, 'Antigua and Barbuda', 2000, 73.6, None),
 (80, 'Argentina', 2015, 76.3, 43417765.0),
 (81, 'Argentina', 2014, 76.2, 42981515.0),
 (82, 'Argentina', 2013, 76.0, 42539925.0),
 (83, 'Argentina', 2012, 75.9, 4296739.0),
 (84, 'Argentina', 2011, 75.7, 41656879.0),
 (85, 'Argentina', 2010, 75.5, 41223889.0),
 (86, 'Argentina', 2009, 75.6, 479947.0),
 (87, 'Argentina', 2008, 75.4, 4382389.0),
 (88, 'Argentina', 2007, 74.8, 3997224.0),
 (89, 'Argentina', 2006, 75.2, 3955889.0),
 (90, 'Argentina', 2005, 74.9, 39145488.0),
 (91, 'Argentina', 2004, 74.7, 38728696.0),
 (92, 'Argentina', 2003, 74.1, 3839379.0),
 (93, 'Argentina', 2002, 74.1, 3788937.0),
 (94, 'Argentina', 2001, 74.0, 3747159.0),
 (95, 'Argentina', 2000, 74.1, 3757452.0),
 (96, 'Armenia', 2015, 74.8, 291695.0),
 (97, 'Armenia', 2014, 74.6, 29622.0),
 (98, 'Armenia', 2013, 74.4, 289359.0),
 (99, 'Armenia', 2012, 74.4, 2881922.0),
 (100, 'Armenia', 2011, 73.9, 2875581.0),
 (101, 'Armenia', 2010, 73.5, 2877311.0),
 (102, 'Armenia', 2009, 73.3, 2888584.0),
 (103, 'Armenia', 2008, 73.2, 29822.0),
 (104, 'Armenia', 2007, 73.5, 293356.0),
 (105, 'Armenia', 2006, 72.9, 29585.0),
 (106, 'Armenia', 2005, 73.0, 2981259.0),
 (107, 'Armenia', 2004, 73.0, 3612.0),
 (108, 'Armenia', 2003, 72.7, 31786.0),
 (109, 'Armenia', 2002, 72.6, 333897.0),
 (110, 'Armenia', 2001, 72.6, 35655.0),
 (111, 'Armenia', 2000, 72.0, 369588.0),
 (112, 'Australia', 2015, 82.8, 23789338.0),
 (113, 'Australia', 2014, 82.7, 2346694.0),
 (114, 'Australia', 2013, 82.5, 23117353.0),
 (115, 'Australia', 2012, 82.3, 22728254.0),
 (116, 'Australia', 2011, 82.0, 223424.0),
 (117, 'Australia', 2010, 81.9, 223175.0),
 (118, 'Australia', 2009, 81.7, 216917.0),
 (119, 'Australia', 2008, 81.3, 212492.0),
 (120, 'Australia', 2007, 81.3, 28276.0),
 (121, 'Australia', 2006, 81.2, 26979.0),
 (122, 'Australia', 2005, 81.0, 23948.0),
 (123, 'Australia', 2004, 86.0, 21274.0),
 (124, 'Australia', 2003, 83.0, 198954.0),
 (125, 'Australia', 2002, 79.9, 196514.0),
 (126, 'Australia', 2001, 79.9, 19413.0),
 (127, 'Australia', 2000, 79.5, 19153.0),
 (128, 'Austria', 2015, 81.5, 8633169.0),
 (129, 'Austria', 2014, 81.4, 8541575.0),
 (130, 'Austria', 2013, 81.1, 8479375.0),
 (131, 'Austria', 2012, 88.0, 8429991.0),
 (132, 'Austria', 2011, 88.0, 8391643.0),
 (133, 'Austria', 2010, 84.0, 836344.0),
 (134, 'Austria', 2009, 82.0, 8343323.0),
 (135, 'Austria', 2008, 84.0, 8321496.0),
 (136, 'Austria', 2007, 81.0, 8295487.0),
 (137, 'Austria', 2006, 79.8, 8268641.0),
 (138, 'Austria', 2005, 79.4, 8227829.0),
 (139, 'Austria', 2004, 79.3, 8171966.0),
 (140, 'Austria', 2003, 78.8, 8121423.0),
 (141, 'Austria', 2002, 78.7, 881957.0),
 (142, 'Austria', 2001, 78.6, 842293.0),
 (143, 'Austria', 2000, 78.1, 811566.0),
 (144, 'Azerbaijan', 2015, 72.7, 9649341.0),
 (145, 'Azerbaijan', 2014, 72.5, 953579.0),
 (146, 'Azerbaijan', 2013, 72.2, 941681.0),
 (147, 'Azerbaijan', 2012, 71.9, 9295784.0),
 (148, 'Azerbaijan', 2011, 71.6, 917382.0),
 (149, 'Azerbaijan', 2010, 71.1, 954332.0),
 (150, 'Azerbaijan', 2009, 78.0, 8947243.0),
 (151, 'Azerbaijan', 2008, 73.0, 87634.0),
 (152, 'Azerbaijan', 2007, 73.0, 85813.0),
 (153, 'Azerbaijan', 2006, 69.2, 848455.0),
 (154, 'Azerbaijan', 2005, 68.4, 839185.0),
 (155, 'Azerbaijan', 2004, 68.4, 8365.0),
 (156, 'Azerbaijan', 2003, 67.8, 82341.0),
 (157, 'Azerbaijan', 2002, 67.8, 817195.0),
 (158, 'Azerbaijan', 2001, 67.5, 81112.0),
 (159, 'Azerbaijan', 2000, 66.6, 8486.0),
 (160, 'Bahamas', 2015, 76.1, None),
 (161, 'Bahamas', 2014, 75.4, None),
 (162, 'Bahamas', 2013, 74.8, None),
 (163, 'Bahamas', 2012, 74.9, None),
 (164, 'Bahamas', 2011, 75.0, None),
 (165, 'Bahamas', 2010, 75.0, None),
 (166, 'Bahamas', 2009, 74.6, None),
 (167, 'Bahamas', 2008, 74.5, None),
 (168, 'Bahamas', 2007, 74.4, None),
 (169, 'Bahamas', 2006, 74.2, None),
 (170, 'Bahamas', 2005, 74.1, None),
 (171, 'Bahamas', 2004, 73.8, None),
 (172, 'Bahamas', 2003, 73.2, None),
 (173, 'Bahamas', 2002, 73.1, None),
 (174, 'Bahamas', 2001, 72.9, None),
 (175, 'Bahamas', 2000, 72.6, None),
 (176, 'Bahrain', 2015, 76.9, None),
 (177, 'Bahrain', 2014, 76.8, None),
 (178, 'Bahrain', 2013, 76.7, None),
 (179, 'Bahrain', 2012, 76.5, None),
 (180, 'Bahrain', 2011, 76.1, None),
 (181, 'Bahrain', 2010, 76.1, None),
 (182, 'Bahrain', 2009, 76.0, None),
 (183, 'Bahrain', 2008, 75.8, None),
 (184, 'Bahrain', 2007, 75.6, None),
 (185, 'Bahrain', 2006, 75.5, None),
 (186, 'Bahrain', 2005, 75.3, None),
 (187, 'Bahrain', 2004, 75.2, None),
 (188, 'Bahrain', 2003, 75.0, None),
 (189, 'Bahrain', 2002, 74.9, None),
 (190, 'Bahrain', 2001, 74.7, None),
 (191, 'Bahrain', 2000, 74.5, None),
 (192, 'Bangladesh', 2015, 71.8, 1612886.0),
 (193, 'Bangladesh', 2014, 71.4, 15945279.0),
 (194, 'Bangladesh', 2013, 71.0, 157571292.0),
 (195, 'Bangladesh', 2012, 77.0, 15572753.0),
 (196, 'Bangladesh', 2011, 73.0, 153911916.0),
 (197, 'Bangladesh', 2010, 69.9, 15214912.0),
 (198, 'Bangladesh', 2009, 69.5, 1545478.0),
 (199, 'Bangladesh', 2008, 69.1, 14885814.0),
 (200, 'Bangladesh', 2007, 68.6, 147139191.0),
 (201, 'Bangladesh', 2006, 68.2, 1453684.0),
 (202, 'Bangladesh', 2005, 67.8, 14343111.0),
 (203, 'Bangladesh', 2004, 67.3, 14137489.0),
 (204, 'Bangladesh', 2003, 66.8, 139191.0),
 (205, 'Bangladesh', 2002, 66.3, 1366667.0),
 (206, 'Bangladesh', 2001, 65.8, 1341716.0),
 (207, 'Bangladesh', 2000, 65.3, 131581243.0),
 (208, 'Barbados', 2015, 75.5, None),
 (209, 'Barbados', 2014, 75.4, None),
 (210, 'Barbados', 2013, 75.2, None),
 (211, 'Barbados', 2012, 75.1, None),
 (212, 'Barbados', 2011, 74.9, None),
 (213, 'Barbados', 2010, 74.7, None),
 (214, 'Barbados', 2009, 74.6, None),
 (215, 'Barbados', 2008, 74.4, None),
 (216, 'Barbados', 2007, 74.2, None),
 (217, 'Barbados', 2006, 74.1, None),
 (218, 'Barbados', 2005, 73.9, None),
 (219, 'Barbados', 2004, 73.8, None),
 (220, 'Barbados', 2003, 73.7, None),
 (221, 'Barbados', 2002, 73.5, None),
 (222, 'Barbados', 2001, 73.4, None),
 (223, 'Barbados', 2000, 73.3, None),
 (224, 'Belarus', 2015, 72.3, 9489616.0),
 (225, 'Belarus', 2014, 72.0, 9474511.0),
 (226, 'Belarus', 2013, 71.7, 9465997.0),
 (227, 'Belarus', 2012, 71.9, 9464495.0),
 (228, 'Belarus', 2011, 72.0, 9473172.0),
 (229, 'Belarus', 2010, 73.0, 949583.0),
 (230, 'Belarus', 2009, 70.0, 956765.0),
 (231, 'Belarus', 2008, 70.0, 9527985.0),
 (232, 'Belarus', 2007, 69.8, 956953.0),
 (233, 'Belarus', 2006, 68.9, 964924.0),
 (234, 'Belarus', 2005, 68.1, 9663915.0),
 (235, 'Belarus', 2004, 68.2, 973146.0),
 (236, 'Belarus', 2003, 67.7, 9796749.0),
 (237, 'Belarus', 2002, 67.2, 9865548.0),
 (238, 'Belarus', 2001, 67.7, 9928549.0),
 (239, 'Belarus', 2000, 68.0, 997961.0),
 (240, 'Belgium', 2015, 81.1, 11274196.0),
 (241, 'Belgium', 2014, 89.0, 112957.0),
 (242, 'Belgium', 2013, 87.0, 11182817.0),
 (243, 'Belgium', 2012, 83.0, 11128246.0),
 (244, 'Belgium', 2011, 83.0, 1147744.0),
 (245, 'Belgium', 2010, 80.0, 1895586.0),
 (246, 'Belgium', 2009, 79.8, 1796493.0),
 (247, 'Belgium', 2008, 79.5, 179973.0),
 (248, 'Belgium', 2007, 79.5, 16257.0),
 (249, 'Belgium', 2006, 79.4, 1547958.0),
 (250, 'Belgium', 2005, 78.9, 1478617.0),
 (251, 'Belgium', 2004, 78.8, 1421137.0),
 (252, 'Belgium', 2003, 78.3, 1376133.0),
 (253, 'Belgium', 2002, 78.0, 1332785.0),
 (254, 'Belgium', 2001, 78.0, 128657.0),
 (255, 'Belgium', 2000, 77.6, 125125.0),
 (256, 'Belize', 2015, 71.0, 359288.0),
 (257, 'Belize', 2014, 70.0, 351694.0),
 (258, 'Belize', 2013, 69.8, 344181.0),
 (259, 'Belize', 2012, 69.4, 33671.0),
 (260, 'Belize', 2011, 69.4, 329192.0),
 (261, 'Belize', 2010, 69.5, 32168.0),
 (262, 'Belize', 2009, 69.5, 313929.0),
 (263, 'Belize', 2008, 69.6, 36165.0),
 (264, 'Belize', 2007, 69.6, 29847.0),
 (265, 'Belize', 2006, 69.4, 29747.0),
 (266, 'Belize', 2005, 69.0, 283277.0),
 (267, 'Belize', 2004, 68.7, 27689.0),
 (268, 'Belize', 2003, 68.4, 26913.0),
 (269, 'Belize', 2002, 68.5, 26226.0),
 (270, 'Belize', 2001, 68.2, 254984.0),
 (271, 'Belize', 2000, 68.3, 247315.0),
 (272, 'Benin', 2015, 60.0, 1575952.0),
 (273, 'Benin', 2014, 59.7, 1286712.0),
 (274, 'Benin', 2013, 59.5, 14451.0),
 (275, 'Benin', 2012, 59.3, 972916.0),
 (276, 'Benin', 2011, 59.1, 94682.0),
 (277, 'Benin', 2010, 58.7, 9199259.0),
 (278, 'Benin', 2009, 58.4, 894476.0),
 (279, 'Benin', 2008, 57.6, 8696916.0),
 (280, 'Benin', 2007, 57.1, 8454791.0),
 (281, 'Benin', 2006, 56.8, 8216896.0),
 (282, 'Benin', 2005, 56.5, 7982225.0),
 (283, 'Benin', 2004, 56.1, 7754.0),
 (284, 'Benin', 2003, 55.8, 752555.0),
 (285, 'Benin', 2002, 55.6, 7295394.0),
 (286, 'Benin', 2001, 55.5, 776733.0),
 (287, 'Benin', 2000, 55.4, 6865951.0),
 (288, 'Bhutan', 2015, 69.8, 787386.0),
 (289, 'Bhutan', 2014, 69.4, 776448.0),
 (290, 'Bhutan', 2013, 69.1, 764961.0),
 (291, 'Bhutan', 2012, 68.7, 752967.0),
 (292, 'Bhutan', 2011, 68.3, 7451.0),
 (293, 'Bhutan', 2010, 67.9, 727641.0),
 (294, 'Bhutan', 2009, 67.4, 714458.0),
 (295, 'Bhutan', 2008, 67.0, 795.0),
 (296, 'Bhutan', 2007, 66.5, 686958.0),
 (297, 'Bhutan', 2006, 65.8, 672228.0),
 (298, 'Bhutan', 2005, 65.0, 656639.0),
 (299, 'Bhutan', 2004, 64.2, 64282.0),
 (300, 'Bhutan', 2003, 63.3, 623434.0),
 (301, 'Bhutan', 2002, 62.5, 66399.0),
 (302, 'Bhutan', 2001, 61.7, 5896.0),
 (303, 'Bhutan', 2000, 62.0, 573416.0),
 (304, 'Bolivia (Plurinational State of)', 2015, 77.0, None),
 (305, 'Bolivia (Plurinational State of)', 2014, 74.0, None),
 (306, 'Bolivia (Plurinational State of)', 2013, 71.0, None),
 (307, 'Bolivia (Plurinational State of)', 2012, 69.8, None),
 (308, 'Bolivia (Plurinational State of)', 2011, 69.3, None),
 (309, 'Bolivia (Plurinational State of)', 2010, 68.7, None),
 (310, 'Bolivia (Plurinational State of)', 2009, 68.0, None),
 (311, 'Bolivia (Plurinational State of)', 2008, 67.4, None),
 (312, 'Bolivia (Plurinational State of)', 2007, 66.8, None),
 (313, 'Bolivia (Plurinational State of)', 2006, 66.2, None),
 (314, 'Bolivia (Plurinational State of)', 2005, 65.7, None),
 (315, 'Bolivia (Plurinational State of)', 2004, 65.1, None),
 (316, 'Bolivia (Plurinational State of)', 2003, 64.5, None),
 (317, 'Bolivia (Plurinational State of)', 2002, 63.9, None),
 (318, 'Bolivia (Plurinational State of)', 2001, 63.3, None),
 (319, 'Bolivia (Plurinational State of)', 2000, 62.6, None),
 (320, 'Bosnia and Herzegovina', 2015, 77.4, 3535961.0),
 (321, 'Bosnia and Herzegovina', 2014, 77.2, 35662.0),
 (322, 'Bosnia and Herzegovina', 2013, 77.0, 364999.0),
 (323, 'Bosnia and Herzegovina', 2012, 76.8, 36482.0),
 (324, 'Bosnia and Herzegovina', 2011, 76.9, 3688865.0),
 (325, 'Bosnia and Herzegovina', 2010, 76.4, 372284.0),
 (326, 'Bosnia and Herzegovina', 2009, 76.1, 3746561.0),
 (327, 'Bosnia and Herzegovina', 2008, 76.0, 3763599.0),
 (328, 'Bosnia and Herzegovina', 2007, 75.4, 3774.0),
 (329, 'Bosnia and Herzegovina', 2006, 75.7, 3779468.0),
 (330, 'Bosnia and Herzegovina', 2005, 75.0, 378153.0),
 (331, 'Bosnia and Herzegovina', 2004, 75.5, 3781287.0),
 (332, 'Bosnia and Herzegovina', 2003, 75.2, 3779247.0),
 (333, 'Bosnia and Herzegovina', 2002, 75.4, 377587.0),
 (334, 'Bosnia and Herzegovina', 2001, 74.9, 3771284.0),
 (335, 'Bosnia and Herzegovina', 2000, 74.6, 376676.0),
 (336, 'Botswana', 2015, 65.7, 229197.0),
 (337, 'Botswana', 2014, 65.1, 2168573.0),
 (338, 'Botswana', 2013, 64.2, 212857.0),
 (339, 'Botswana', 2012, 63.4, 289315.0),
 (340, 'Botswana', 2011, 62.2, 251339.0),
 (341, 'Botswana', 2010, 61.1, 214866.0),
 (342, 'Botswana', 2009, 59.2, 1979882.0),
 (343, 'Botswana', 2008, 57.5, 1946351.0),
 (344, 'Botswana', 2007, 56.9, 1914414.0),
 (345, 'Botswana', 2006, 54.8, 1884238.0),
 (346, 'Botswana', 2005, 51.7, 1855852.0),
 (347, 'Botswana', 2004, 48.1, 182933.0),
 (348, 'Botswana', 2003, 46.4, 184339.0),
 (349, 'Botswana', 2002, 46.0, 1779953.0),
 (350, 'Botswana', 2001, 46.7, 1754935.0),
 (351, 'Botswana', 2000, 47.8, 172834.0),
 (352, 'Brazil', 2015, 75.0, 2596218.0),
 (353, 'Brazil', 2014, 74.8, 24213133.0),
 (354, 'Brazil', 2013, 74.7, 2248632.0),
 (355, 'Brazil', 2012, 74.5, 256983.0),
 (356, 'Brazil', 2011, 74.1, 198686688.0),
 (357, 'Brazil', 2010, 73.8, 196796269.0),
 (358, 'Brazil', 2009, 73.6, 194895996.0),
 (359, 'Brazil', 2008, 73.4, 19297929.0),
 (360, 'Brazil', 2007, 73.3, 19126637.0),
 (361, 'Brazil', 2006, 73.0, 18912412.0),
 (362, 'Brazil', 2005, 72.7, 186917361.0),
 (363, 'Brazil', 2004, 72.0, 184738458.0),
 (364, 'Brazil', 2003, 71.8, 182482149.0),
 (365, 'Brazil', 2002, 71.4, 1815121.0),
 (366, 'Brazil', 2001, 71.0, 1777567.0),
 (367, 'Brazil', 2000, 75.0, 175287587.0),
 (368, 'Brunei Darussalam', 2015, 77.7, None),
 (369, 'Brunei Darussalam', 2014, 77.6, None),
 (370, 'Brunei Darussalam', 2013, 77.1, None),
 (371, 'Brunei Darussalam', 2012, 78.3, None),
 (372, 'Brunei Darussalam', 2011, 77.4, None),
 (373, 'Brunei Darussalam', 2010, 76.9, None),
 (374, 'Brunei Darussalam', 2009, 76.8, None),
 (375, 'Brunei Darussalam', 2008, 77.2, None),
 (376, 'Brunei Darussalam', 2007, 76.0, None),
 (377, 'Brunei Darussalam', 2006, 76.3, None),
 (378, 'Brunei Darussalam', 2005, 76.2, None),
 (379, 'Brunei Darussalam', 2004, 76.4, None),
 (380, 'Brunei Darussalam', 2003, 76.0, None),
 (381, 'Brunei Darussalam', 2002, 74.8, None),
 (382, 'Brunei Darussalam', 2001, 74.7, None),
 (383, 'Brunei Darussalam', 2000, 74.4, None),
 (384, 'Bulgaria', 2015, 74.5, 7177991.0),
 (385, 'Bulgaria', 2014, 74.3, 7223938.0),
 (386, 'Bulgaria', 2013, 74.1, 7265115.0),
 (387, 'Bulgaria', 2012, 73.9, 735888.0),
 (388, 'Bulgaria', 2011, 73.7, 7348328.0),
 (389, 'Bulgaria', 2010, 73.4, 7395599.0),
 (390, 'Bulgaria', 2009, 73.2, 7444443.0),
 (391, 'Bulgaria', 2008, 72.9, 7492561.0),
 (392, 'Bulgaria', 2007, 72.6, 7545338.0),
 (393, 'Bulgaria', 2006, 72.2, 76122.0),
 (394, 'Bulgaria', 2005, 72.1, 7658972.0),
 (395, 'Bulgaria', 2004, 72.2, 771686.0),
 (396, 'Bulgaria', 2003, 72.0, 7775327.0),
 (397, 'Bulgaria', 2002, 71.8, 7837161.0),
 (398, 'Bulgaria', 2001, 71.6, 89142.0),
 (399, 'Bulgaria', 2000, 71.1, 817172.0),
 (400, 'Burkina Faso', 2015, 59.9, 1811624.0),
 (401, 'Burkina Faso', 2014, 59.3, 17585977.0),
 (402, 'Burkina Faso', 2013, 59.0, 1772723.0),
 (403, 'Burkina Faso', 2012, 58.6, 16571216.0),
 (404, 'Burkina Faso', 2011, 58.1, 168194.0),
 (405, 'Burkina Faso', 2010, 57.5, 1565217.0),
 (406, 'Burkina Faso', 2009, 56.9, 1514199.0),
 (407, 'Burkina Faso', 2008, 56.1, 14689726.0),
 (408, 'Burkina Faso', 2007, 55.3, 1425221.0),
 (409, 'Burkina Faso', 2006, 54.3, 13829177.0),
 (410, 'Burkina Faso', 2005, 53.3, 1342193.0),
 (411, 'Burkina Faso', 2004, 52.4, 133569.0),
 (412, 'Burkina Faso', 2003, 51.6, 12654621.0),
 (413, 'Burkina Faso', 2002, 51.0, 122931.0),
 (414, 'Burkina Faso', 2001, 56.0, 11944587.0),
 (415, 'Burkina Faso', 2000, 51.0, 1167942.0),
 (416, 'Burundi', 2015, 59.6, 119927.0),
 (417, 'Burundi', 2014, 59.1, 989179.0),
 (418, 'Burundi', 2013, 58.6, 96186.0),
 (419, 'Burundi', 2012, 58.0, 931971.0),
 (420, 'Burundi', 2011, 57.4, 94358.0),
 (421, 'Burundi', 2010, 56.8, 876693.0),
 (422, 'Burundi', 2009, 56.2, 848931.0),
 (423, 'Burundi', 2008, 55.3, 8212264.0),
 (424, 'Burundi', 2007, 54.8, 7939573.0),
 (425, 'Burundi', 2006, 54.1, 7675338.0),
 (426, 'Burundi', 2005, 53.4, 7423289.0),
 (427, 'Burundi', 2004, 52.6, 7182451.0),
 (428, 'Burundi', 2003, 51.9, 6953113.0),
 (429, 'Burundi', 2002, 51.5, 6741569.0),
 (430, 'Burundi', 2001, 51.3, 6555829.0),
 (431, 'Burundi', 2000, 58.0, 6476.0),
 (432, "CÃ´te d'Ivoire", 2015, 53.3, None),
 (433, "CÃ´te d'Ivoire", 2014, 52.8, None),
 (434, "CÃ´te d'Ivoire", 2013, 52.3, None),
 (435, "CÃ´te d'Ivoire", 2012, 52.0, None),
 (436, "CÃ´te d'Ivoire", 2011, 51.7, None),
 (437, "CÃ´te d'Ivoire", 2010, 51.5, None),
 (438, "CÃ´te d'Ivoire", 2009, 51.0, None),
 (439, "CÃ´te d'Ivoire", 2008, 54.0, None),
 (440, "CÃ´te d'Ivoire", 2007, 49.9, None),
 (441, "CÃ´te d'Ivoire", 2006, 49.4, None),
 (442, "CÃ´te d'Ivoire", 2005, 48.7, None),
 (443, "CÃ´te d'Ivoire", 2004, 48.2, None),
 (444, "CÃ´te d'Ivoire", 2003, 48.0, None),
 (445, "CÃ´te d'Ivoire", 2002, 47.7, None),
 (446, "CÃ´te d'Ivoire", 2001, 47.8, None),
 (447, "CÃ´te d'Ivoire", 2000, 47.9, None),
 (448, 'Cabo Verde', 2015, 73.3, 532913.0),
 (449, 'Cabo Verde', 2014, 73.0, 526437.0),
 (450, 'Cabo Verde', 2013, 72.8, 5216.0),
 (451, 'Cabo Verde', 2012, 72.7, 513979.0),
 (452, 'Cabo Verde', 2011, 72.6, 5867.0),
 (453, 'Cabo Verde', 2010, 72.5, 52384.0),
 (454, 'Cabo Verde', 2009, 72.4, 496963.0),
 (455, 'Cabo Verde', 2008, 72.4, 491723.0),
 (456, 'Cabo Verde', 2007, 72.3, 486438.0),
 (457, 'Cabo Verde', 2006, 72.1, 48795.0),
 (458, 'Cabo Verde', 2005, 71.8, 474567.0),
 (459, 'Cabo Verde', 2004, 71.4, 467664.0),
 (460, 'Cabo Verde', 2003, 71.1, 46147.0),
 (461, 'Cabo Verde', 2002, 77.0, 45216.0),

In [125]:
#World Happiness Report 2015:Convert Pandas to SQL
WH_15_edit.to_sql(name='world_happiness_15', con=engine)

ValueError: Table 'world_happiness_15' already exists.

In [126]:
#World Happiness Report 2015: Convert Pandas to SQL
engine.execute("SELECT * FROM world_happiness_15").fetchall()

[(0, 'Switzerland', 1, 7.587),
 (1, 'Iceland', 2, 7.561),
 (2, 'Denmark', 3, 7.527),
 (3, 'Norway', 4, 7.522),
 (4, 'Canada', 5, 7.427),
 (5, 'Finland', 6, 7.406),
 (6, 'Netherlands', 7, 7.378),
 (7, 'Sweden', 8, 7.364),
 (8, 'New Zealand', 9, 7.286),
 (9, 'Australia', 10, 7.284),
 (10, 'Israel', 11, 7.278),
 (11, 'Costa Rica', 12, 7.226),
 (12, 'Austria', 13, 7.2),
 (13, 'Mexico', 14, 7.187),
 (14, 'United States', 15, 7.119),
 (15, 'Brazil', 16, 6.983),
 (16, 'Luxembourg', 17, 6.946),
 (17, 'Ireland', 18, 6.94),
 (18, 'Belgium', 19, 6.937),
 (19, 'United Arab Emirates', 20, 6.901),
 (20, 'United Kingdom', 21, 6.867),
 (21, 'Oman', 22, 6.853),
 (22, 'Venezuela', 23, 6.81),
 (23, 'Singapore', 24, 6.798),
 (24, 'Panama', 25, 6.786),
 (25, 'Germany', 26, 6.75),
 (26, 'Chile', 27, 6.67),
 (27, 'Qatar', 28, 6.611),
 (28, 'France', 29, 6.575),
 (29, 'Argentina', 30, 6.574),
 (30, 'Czech Republic', 31, 6.505),
 (31, 'Uruguay', 32, 6.485),
 (32, 'Colombia', 33, 6.477),
 (33, 'Thailand', 34, 6.455),
 (34, 'Saudi Arabia', 35, 6.411),
 (35, 'Spain', 36, 6.329),
 (36, 'Malta', 37, 6.302),
 (37, 'Taiwan', 38, 6.298),
 (38, 'Kuwait', 39, 6.295),
 (39, 'Suriname', 40, 6.269),
 (40, 'Trinidad and Tobago', 41, 6.168),
 (41, 'El Salvador', 42, 6.13),
 (42, 'Guatemala', 43, 6.123),
 (43, 'Uzbekistan', 44, 6.003),
 (44, 'Slovakia', 45, 5.995),
 (45, 'Japan', 46, 5.987),
 (46, 'South Korea', 47, 5.984),
 (47, 'Ecuador', 48, 5.975),
 (48, 'Bahrain', 49, 5.96),
 (49, 'Italy', 50, 5.948),
 (50, 'Bolivia', 51, 5.89),
 (51, 'Moldova', 52, 5.889),
 (52, 'Paraguay', 53, 5.878),
 (53, 'Kazakhstan', 54, 5.855),
 (54, 'Slovenia', 55, 5.848),
 (55, 'Lithuania', 56, 5.833),
 (56, 'Nicaragua', 57, 5.828),
 (57, 'Peru', 58, 5.824),
 (58, 'Belarus', 59, 5.813),
 (59, 'Poland', 60, 5.791),
 (60, 'Malaysia', 61, 5.77),
 (61, 'Croatia', 62, 5.759),
 (62, 'Libya', 63, 5.754),
 (63, 'Russia', 64, 5.716),
 (64, 'Jamaica', 65, 5.709),
 (65, 'North Cyprus', 66, 5.695),
 (66, 'Cyprus', 67, 5.689),
 (67, 'Algeria', 68, 5.605),
 (68, 'Kosovo', 69, 5.589),
 (69, 'Turkmenistan', 70, 5.548),
 (70, 'Mauritius', 71, 5.477),
 (71, 'Hong Kong', 72, 5.474),
 (72, 'Estonia', 73, 5.429),
 (73, 'Indonesia', 74, 5.399),
 (74, 'Vietnam', 75, 5.36),
 (75, 'Turkey', 76, 5.332),
 (76, 'Kyrgyzstan', 77, 5.286),
 (77, 'Nigeria', 78, 5.268),
 (78, 'Bhutan', 79, 5.253),
 (79, 'Azerbaijan', 80, 5.212),
 (80, 'Pakistan', 81, 5.194),
 (81, 'Jordan', 82, 5.192),
 (82, 'Montenegro', 82, 5.192),
 (83, 'China', 84, 5.14),
 (84, 'Zambia', 85, 5.129),
 (85, 'Romania', 86, 5.124),
 (86, 'Serbia', 87, 5.123),
 (87, 'Portugal', 88, 5.102),
 (88, 'Latvia', 89, 5.098),
 (89, 'Philippines', 90, 5.073),
 (90, 'Somaliland region', 91, 5.057),
 (91, 'Morocco', 92, 5.013),
 (92, 'Macedonia', 93, 5.007),
 (93, 'Mozambique', 94, 4.971),
 (94, 'Albania', 95, 4.959),
 (95, 'Bosnia and Herzegovina', 96, 4.949),
 (96, 'Lesotho', 97, 4.898),
 (97, 'Dominican Republic', 98, 4.885),
 (98, 'Laos', 99, 4.876),
 (99, 'Mongolia', 100, 4.874),
 (100, 'Swaziland', 101, 4.867),
 (101, 'Greece', 102, 4.857),
 (102, 'Lebanon', 103, 4.839),
 (103, 'Hungary', 104, 4.8),
 (104, 'Honduras', 105, 4.788),
 (105, 'Tajikistan', 106, 4.786),
 (106, 'Tunisia', 107, 4.739),
 (107, 'Palestinian Territories', 108, 4.715),
 (108, 'Bangladesh', 109, 4.694),
 (109, 'Iran', 110, 4.686),
 (110, 'Ukraine', 111, 4.681),
 (111, 'Iraq', 112, 4.677),
 (112, 'South Africa', 113, 4.642),
 (113, 'Ghana', 114, 4.633),
 (114, 'Zimbabwe', 115, 4.61),
 (115, 'Liberia', 116, 4.571),
 (116, 'India', 117, 4.565),
 (117, 'Sudan', 118, 4.55),
 (118, 'Haiti', 119, 4.518),
 (119, 'Congo (Kinshasa)', 120, 4.517),
 (120, 'Nepal', 121, 4.514),
 (121, 'Ethiopia', 122, 4.512),
 (122, 'Sierra Leone', 123, 4.507),
 (123, 'Mauritania', 124, 4.436),
 (124, 'Kenya', 125, 4.419),
 (125, 'Djibouti', 126, 4.369),
 (126, 'Armenia', 127, 4.35),
 (127, 'Botswana', 128, 4.332),
 (128, 'Myanmar', 129, 4.307),
 (129, 'Georgia', 130, 4.297),
 (130, 'Malawi', 131, 4.292),
 (131, 'Sri Lanka', 132, 4.271),
 (132, 'Cameroon', 133, 4.252),
 (133, 'Bulgaria', 134, 4.218),
 (134, 'Egypt', 135, 4.194),
 (135, 'Yemen', 136, 4.077),
 (136, 'Angola', 137, 4.033),
 (137, 'Mali', 138, 3.995),
 (138, 'Congo (Brazzaville)', 139, 3.989),
 (139, 'Comoros', 140, 3.956),
 (140, 'Uganda', 141, 3.931),
 (141, 'Senegal', 142, 3.904),
 (142, 'Gabon', 143, 3.896),
 (143, 'Niger', 144, 3.845),
 (144, 'Cambodia', 145, 3.819),
 (145, 'Tanzania', 146, 3.781),
 (146, 'Madagascar', 147, 3.681),
 (147, 'Central African Republic', 148, 3.678),
 (148, 'Chad', 149, 3.667),
 (149, 'Guinea', 150, 3.656),
 (150, 'Ivory Coast', 151, 3.655),
 (151, 'Burkina Faso', 152, 3.587),
 (152, 'Afghanistan', 153, 3.575),
 (153, 'Rwanda', 154, 3.465),
 (154, 'Benin', 155, 3.34),
 (155, 'Syria', 156, 3.006),
 (156, 'Burundi', 157, 2.905),
 (157, 'Togo', 158, 2.839)]

In [127]:
#World Happiness Report 2016: Convert Pandas to SQL
WH_16_edit.to_sql(name='world_happiness_16', con=engine)

ValueError: Table 'world_happiness_16' already exists.

In [128]:
#World Happiness Report 2016: Fetch all data from table
engine.execute("SELECT * FROM world_happiness_16").fetchall()

[(0, 'Denmark', 1, 7.526),
 (1, 'Switzerland', 2, 7.509),
 (2, 'Iceland', 3, 7.501),
 (3, 'Norway', 4, 7.498),
 (4, 'Finland', 5, 7.413),
 (5, 'Canada', 6, 7.404),
 (6, 'Netherlands', 7, 7.339),
 (7, 'New Zealand', 8, 7.334),
 (8, 'Australia', 9, 7.313),
 (9, 'Sweden', 10, 7.291),
 (10, 'Israel', 11, 7.267),
 (11, 'Austria', 12, 7.119),
 (12, 'United States', 13, 7.104),
 (13, 'Costa Rica', 14, 7.087),
 (14, 'Puerto Rico', 15, 7.039),
 (15, 'Germany', 16, 6.994),
 (16, 'Brazil', 17, 6.952),
 (17, 'Belgium', 18, 6.929),
 (18, 'Ireland', 19, 6.907),
 (19, 'Luxembourg', 20, 6.871),
 (20, 'Mexico', 21, 6.778),
 (21, 'Singapore', 22, 6.739),
 (22, 'United Kingdom', 23, 6.725),
 (23, 'Chile', 24, 6.705),
 (24, 'Panama', 25, 6.701),
 (25, 'Argentina', 26, 6.65),
 (26, 'Czech Republic', 27, 6.596),
 (27, 'United Arab Emirates', 28, 6.573),
 (28, 'Uruguay', 29, 6.545),
 (29, 'Malta', 30, 6.488),
 (30, 'Colombia', 31, 6.481),
 (31, 'France', 32, 6.478),
 (32, 'Thailand', 33, 6.474),
 (33, 'Saudi Arabia', 34, 6.379),
 (34, 'Taiwan', 34, 6.379),
 (35, 'Qatar', 36, 6.375),
 (36, 'Spain', 37, 6.361),
 (37, 'Algeria', 38, 6.355),
 (38, 'Guatemala', 39, 6.324),
 (39, 'Suriname', 40, 6.269),
 (40, 'Kuwait', 41, 6.239),
 (41, 'Bahrain', 42, 6.218),
 (42, 'Trinidad and Tobago', 43, 6.168),
 (43, 'Venezuela', 44, 6.084),
 (44, 'Slovakia', 45, 6.078),
 (45, 'El Salvador', 46, 6.068),
 (46, 'Malaysia', 47, 6.005),
 (47, 'Nicaragua', 48, 5.992),
 (48, 'Uzbekistan', 49, 5.987),
 (49, 'Italy', 50, 5.977),
 (50, 'Ecuador', 51, 5.976),
 (51, 'Belize', 52, 5.956),
 (52, 'Japan', 53, 5.921),
 (53, 'Kazakhstan', 54, 5.919),
 (54, 'Moldova', 55, 5.897),
 (55, 'Russia', 56, 5.856),
 (56, 'Poland', 57, 5.835),
 (57, 'South Korea', 57, 5.835),
 (58, 'Bolivia', 59, 5.822),
 (59, 'Lithuania', 60, 5.813),
 (60, 'Belarus', 61, 5.802),
 (61, 'North Cyprus', 62, 5.771),
 (62, 'Slovenia', 63, 5.768),
 (63, 'Peru', 64, 5.743),
 (64, 'Turkmenistan', 65, 5.658),
 (65, 'Mauritius', 66, 5.648),
 (66, 'Libya', 67, 5.615),
 (67, 'Latvia', 68, 5.56),
 (68, 'Cyprus', 69, 5.546),
 (69, 'Paraguay', 70, 5.538),
 (70, 'Romania', 71, 5.528),
 (71, 'Estonia', 72, 5.517),
 (72, 'Jamaica', 73, 5.51),
 (73, 'Croatia', 74, 5.488),
 (74, 'Hong Kong', 75, 5.458),
 (75, 'Somalia', 76, 5.44),
 (76, 'Kosovo', 77, 5.401),
 (77, 'Turkey', 78, 5.389),
 (78, 'Indonesia', 79, 5.314),
 (79, 'Jordan', 80, 5.303),
 (80, 'Azerbaijan', 81, 5.291),
 (81, 'Philippines', 82, 5.279),
 (82, 'China', 83, 5.245),
 (83, 'Bhutan', 84, 5.196),
 (84, 'Kyrgyzstan', 85, 5.185),
 (85, 'Serbia', 86, 5.177),
 (86, 'Bosnia and Herzegovina', 87, 5.163),
 (87, 'Montenegro', 88, 5.161),
 (88, 'Dominican Republic', 89, 5.155),
 (89, 'Morocco', 90, 5.151),
 (90, 'Hungary', 91, 5.145),
 (91, 'Pakistan', 92, 5.132),
 (92, 'Lebanon', 93, 5.129),
 (93, 'Portugal', 94, 5.123),
 (94, 'Macedonia', 95, 5.121),
 (95, 'Vietnam', 96, 5.061),
 (96, 'Somaliland Region', 97, 5.057),
 (97, 'Tunisia', 98, 5.045),
 (98, 'Greece', 99, 5.033),
 (99, 'Tajikistan', 100, 4.996),
 (100, 'Mongolia', 101, 4.907),
 (101, 'Laos', 102, 4.876),
 (102, 'Nigeria', 103, 4.875),
 (103, 'Honduras', 104, 4.871),
 (104, 'Iran', 105, 4.813),
 (105, 'Zambia', 106, 4.795),
 (106, 'Nepal', 107, 4.793),
 (107, 'Palestinian Territories', 108, 4.754),
 (108, 'Albania', 109, 4.655),
 (109, 'Bangladesh', 110, 4.643),
 (110, 'Sierra Leone', 111, 4.635),
 (111, 'Iraq', 112, 4.575),
 (112, 'Namibia', 113, 4.574),
 (113, 'Cameroon', 114, 4.513),
 (114, 'Ethiopia', 115, 4.508),
 (115, 'South Africa', 116, 4.459),
 (116, 'Sri Lanka', 117, 4.415),
 (117, 'India', 118, 4.404),
 (118, 'Myanmar', 119, 4.395),
 (119, 'Egypt', 120, 4.362),
 (120, 'Armenia', 121, 4.36),
 (121, 'Kenya', 122, 4.356),
 (122, 'Ukraine', 123, 4.324),
 (123, 'Ghana', 124, 4.276),
 (124, 'Congo (Kinshasa)', 125, 4.272),
 (125, 'Georgia', 126, 4.252),
 (126, 'Congo (Brazzaville)', 127, 4.236),
 (127, 'Senegal', 128, 4.219),
 (128, 'Bulgaria', 129, 4.217),
 (129, 'Mauritania', 130, 4.201),
 (130, 'Zimbabwe', 131, 4.193),
 (131, 'Malawi', 132, 4.156),
 (132, 'Sudan', 133, 4.139),
 (133, 'Gabon', 134, 4.121),
 (134, 'Mali', 135, 4.073),
 (135, 'Haiti', 136, 4.028),
 (136, 'Botswana', 137, 3.974),
 (137, 'Comoros', 138, 3.956),
 (138, 'Ivory Coast', 139, 3.916),
 (139, 'Cambodia', 140, 3.907),
 (140, 'Angola', 141, 3.866),
 (141, 'Niger', 142, 3.856),
 (142, 'South Sudan', 143, 3.832),
 (143, 'Chad', 144, 3.763),
 (144, 'Burkina Faso', 145, 3.739),
 (145, 'Uganda', 145, 3.739),
 (146, 'Yemen', 147, 3.724),
 (147, 'Madagascar', 148, 3.695),
 (148, 'Tanzania', 149, 3.666),
 (149, 'Liberia', 150, 3.622),
 (150, 'Guinea', 151, 3.607),
 (151, 'Rwanda', 152, 3.515),
 (152, 'Benin', 153, 3.484),
 (153, 'Afghanistan', 154, 3.36),
 (154, 'Togo', 155, 3.303),
 (155, 'Syria', 156, 3.069),
 (156, 'Burundi', 157, 2.905)]

In [129]:
#World Happiness Report 2017: Convert Pandas to SQL
WH_17_edit.to_sql(name='world_happiness_17', con=engine)

ValueError: Table 'world_happiness_17' already exists.

In [143]:
#World Happiness Report 2017: Fetch all data from table
engine.execute("SELECT * FROM world_happiness_17").fetchall()

[(0, 'Norway', 1, 7.53700017929077),
 (1, 'Denmark', 2, 7.52199983596802),
 (2, 'Iceland', 3, 7.50400018692017),
 (3, 'Switzerland', 4, 7.49399995803833),
 (4, 'Finland', 5, 7.4689998626709),
 (5, 'Netherlands', 6, 7.3769998550415),
 (6, 'Canada', 7, 7.31599998474121),
 (7, 'New Zealand', 8, 7.31400012969971),
 (8, 'Sweden', 9, 7.28399991989136),
 (9, 'Australia', 10, 7.28399991989136),
 (10, 'Israel', 11, 7.21299982070923),
 (11, 'Costa Rica', 12, 7.0789999961853),
 (12, 'Austria', 13, 7.00600004196167),
 (13, 'United States', 14, 6.99300003051758),
 (14, 'Ireland', 15, 6.97700023651123),
 (15, 'Germany', 16, 6.95100021362305),
 (16, 'Belgium', 17, 6.89099979400635),
 (17, 'Luxembourg', 18, 6.86299991607666),
 (18, 'United Kingdom', 19, 6.71400022506714),
 (19, 'Chile', 20, 6.65199995040894),
 (20, 'United Arab Emirates', 21, 6.64799976348877),
 (21, 'Brazil', 22, 6.63500022888184),
 (22, 'Czech Republic', 23, 6.60900020599365),
 (23, 'Argentina', 24, 6.59899997711182),
 (24, 'Mexico', 25, 6.57800006866455),
 (25, 'Singapore', 26, 6.57200002670288),
 (26, 'Malta', 27, 6.52699995040894),
 (27, 'Uruguay', 28, 6.4539999961853),
 (28, 'Guatemala', 29, 6.4539999961853),
 (29, 'Panama', 30, 6.4520001411438),
 (30, 'France', 31, 6.44199991226196),
 (31, 'Thailand', 32, 6.42399978637695),
 (32, 'Taiwan Province of China', 33, 6.42199993133545),
 (33, 'Spain', 34, 6.40299987792969),
 (34, 'Qatar', 35, 6.375),
 (35, 'Colombia', 36, 6.35699987411499),
 (36, 'Saudi Arabia', 37, 6.3439998626709),
 (37, 'Trinidad and Tobago', 38, 6.16800022125244),
 (38, 'Kuwait', 39, 6.10500001907349),
 (39, 'Slovakia', 40, 6.09800004959106),
 (40, 'Bahrain', 41, 6.08699989318848),
 (41, 'Malaysia', 42, 6.08400011062622),
 (42, 'Nicaragua', 43, 6.07100009918213),
 (43, 'Ecuador', 44, 6.00799989700317),
 (44, 'El Salvador', 45, 6.00299978256226),
 (45, 'Poland', 46, 5.97300004959106),
 (46, 'Uzbekistan', 47, 5.97100019454956),
 (47, 'Italy', 48, 5.96400022506714),
 (48, 'Russia', 49, 5.96299982070923),
 (49, 'Belize', 50, 5.95599985122681),
 (50, 'Japan', 51, 5.92000007629395),
 (51, 'Lithuania', 52, 5.90199995040894),
 (52, 'Algeria', 53, 5.87200021743774),
 (53, 'Latvia', 54, 5.84999990463257),
 (54, 'South Korea', 55, 5.83799982070923),
 (55, 'Moldova', 56, 5.83799982070923),
 (56, 'Romania', 57, 5.82499980926514),
 (57, 'Bolivia', 58, 5.82299995422363),
 (58, 'Turkmenistan', 59, 5.82200002670288),
 (59, 'Kazakhstan', 60, 5.81899976730347),
 (60, 'North Cyprus', 61, 5.80999994277954),
 (61, 'Slovenia', 62, 5.75799989700317),
 (62, 'Peru', 63, 5.71500015258789),
 (63, 'Mauritius', 64, 5.62900018692017),
 (64, 'Cyprus', 65, 5.62099981307983),
 (65, 'Estonia', 66, 5.61100006103516),
 (66, 'Belarus', 67, 5.56899976730347),
 (67, 'Libya', 68, 5.52500009536743),
 (68, 'Turkey', 69, 5.5),
 (69, 'Paraguay', 70, 5.49300003051758),
 (70, 'Hong Kong S.A.R., China', 71, 5.47200012207031),
 (71, 'Philippines', 72, 5.42999982833862),
 (72, 'Serbia', 73, 5.39499998092651),
 (73, 'Jordan', 74, 5.33599996566772),
 (74, 'Hungary', 75, 5.32399988174438),
 (75, 'Jamaica', 76, 5.31099987030029),
 (76, 'Croatia', 77, 5.29300022125244),
 (77, 'Kosovo', 78, 5.27899980545044),
 (78, 'China', 79, 5.27299976348877),
 (79, 'Pakistan', 80, 5.26900005340576),
 (80, 'Indonesia', 81, 5.26200008392334),
 (81, 'Venezuela', 82, 5.25),
 (82, 'Montenegro', 83, 5.23699998855591),
 (83, 'Morocco', 84, 5.2350001335144),
 (84, 'Azerbaijan', 85, 5.23400020599365),
 (85, 'Dominican Republic', 86, 5.23000001907349),
 (86, 'Greece', 87, 5.22700023651123),
 (87, 'Lebanon', 88, 5.22499990463257),
 (88, 'Portugal', 89, 5.19500017166138),
 (89, 'Bosnia and Herzegovina', 90, 5.18200016021729),
 (90, 'Honduras', 91, 5.18100023269653),
 (91, 'Macedonia', 92, 5.17500019073486),
 (92, 'Somalia', 93, 5.15100002288818),
 (93, 'Vietnam', 94, 5.07399988174438),
 (94, 'Nigeria', 95, 5.07399988174438),
 (95, 'Tajikistan', 96, 5.04099988937378),
 (96, 'Bhutan', 97, 5.01100015640259),
 (97, 'Kyrgyzstan', 98, 5.00400018692017),
 (98, 'Nepal', 99, 4.96199989318848),
 (99, 'Mongolia', 100, 4.95499992370605),
 (100, 'South Africa', 101, 4.8289999961853),
 (101, 'Tunisia', 102, 4.80499982833862),
 (102, 'Palestinian Territories', 103, 4.77500009536743),
 (103, 'Egypt', 104, 4.7350001335144),
 (104, 'Bulgaria', 105, 4.71400022506714),
 (105, 'Sierra Leone', 106, 4.70900011062622),
 (106, 'Cameroon', 107, 4.69500017166138),
 (107, 'Iran', 108, 4.69199991226196),
 (108, 'Albania', 109, 4.64400005340576),
 (109, 'Bangladesh', 110, 4.60799980163574),
 (110, 'Namibia', 111, 4.57399988174438),
 (111, 'Kenya', 112, 4.55299997329712),
 (112, 'Mozambique', 113, 4.55000019073486),
 (113, 'Myanmar', 114, 4.54500007629395),
 (114, 'Senegal', 115, 4.53499984741211),
 (115, 'Zambia', 116, 4.51399993896484),
 (116, 'Iraq', 117, 4.49700021743774),
 (117, 'Gabon', 118, 4.46500015258789),
 (118, 'Ethiopia', 119, 4.46000003814697),
 (119, 'Sri Lanka', 120, 4.44000005722046),
 (120, 'Armenia', 121, 4.37599992752075),
 (121, 'India', 122, 4.31500005722046),
 (122, 'Mauritania', 123, 4.29199981689453),
 (123, 'Congo (Brazzaville)', 124, 4.29099988937378),
 (124, 'Georgia', 125, 4.28599977493286),
 (125, 'Congo (Kinshasa)', 126, 4.28000020980835),
 (126, 'Mali', 127, 4.19000005722046),
 (127, 'Ivory Coast', 128, 4.17999982833862),
 (128, 'Cambodia', 129, 4.16800022125244),
 (129, 'Sudan', 130, 4.13899993896484),
 (130, 'Ghana', 131, 4.11999988555908),
 (131, 'Ukraine', 132, 4.09600019454956),
 (132, 'Uganda', 133, 4.08099985122681),
 (133, 'Burkina Faso', 134, 4.03200006484985),
 (134, 'Niger', 135, 4.02799987792969),
 (135, 'Malawi', 136, 3.97000002861023),
 (136, 'Chad', 137, 3.93600010871887),
 (137, 'Zimbabwe', 138, 3.875),
 (138, 'Lesotho', 139, 3.80800008773804),
 (139, 'Angola', 140, 3.79500007629395),
 (140, 'Afghanistan', 141, 3.79399991035461),
 (141, 'Botswana', 142, 3.76600003242493),
 (142, 'Benin', 143, 3.65700006484985),
 (143, 'Madagascar', 144, 3.64400005340576),
 (144, 'Haiti', 145, 3.6029999256134),
 (145, 'Yemen', 146, 3.59299993515015),
 (146, 'South Sudan', 147, 3.59100008010864),
 (147, 'Liberia', 148, 3.53299999237061),
 (148, 'Guinea', 149, 3.50699996948242),
 (149, 'Togo', 150, 3.49499988555908),
 (150, 'Rwanda', 151, 3.47099995613098),
 (151, 'Syria', 152, 3.46199989318848),
 (152, 'Tanzania', 153, 3.34899997711182),
 (153, 'Burundi', 154, 2.90499997138977),
 (154, 'Central African Republic', 155, 2.69300007820129)]

In [131]:
#World Happiness Report 2015: Testing db connection
pd.read_sql_query('select * from world_happiness_15', con=engine).head()

   index      country  happiness_rank  happiness_score
0      0  Switzerland               1            7.587
1      1      Iceland               2            7.561
2      2      Denmark               3            7.527
3      3       Norway               4            7.522
4      4       Canada               5            7.427

In [132]:
#World Happiness Report 2016: Testing db connection
pd.read_sql_query('select * from world_happiness_16', con=engine).head()

   index      country  happiness_rank  happiness_score
0      0      Denmark               1            7.526
1      1  Switzerland               2            7.509
2      2      Iceland               3            7.501
3      3       Norway               4            7.498
4      4      Finland               5            7.413

In [133]:
#World Happiness Report 2017: Testing db connection
pd.read_sql_query('select * from world_happiness_17', con=engine).head()

   index      country  happiness_rank  happiness_score
0      0       Norway               1            7.537
1      1      Denmark               2            7.522
2      2      Iceland               3            7.504
3      3  Switzerland               4            7.494
4      4      Finland               5            7.469

In [145]:
#Economic Freedom: Testing db connection
pd.read_sql_query('select * from free_ecos_4', con=engine).head()

,CountryID,Country_Name,WEBNAME,Region,World_Rank,Region_Rank,2019_Score,Property_Rights,Judical_Effectiveness,Government_Integrity,...,Govt_Expenditure_of_GDP,Population_Millions,GDP_Billions_PPP,GDP_Growth_Rate,5_Year_GDP_Growth_Rate,GDP_per_Capita_PPP,Unemployment,Inflation,FDI_Inflow_Millions,Public_Debtof_GDP
0,1,Afghanistan,Afghanistan,Asia-Pacific,152,39,51.5,19.6,29.6,25.2,...,25.6,35.5,69.6,2.5,2.9,1958,8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52,27,66.5,54.8,30.6,40.4,...,29.5,2.9,36.0,3.9,2.5,12507,13.9,2.0,1119.1,71.2
2,3,Algeria,Algeria,Middle East and North Africa,171,14,46.2,31.6,36.2,28.9,...,41.4,41.5,632.9,2.0,3.1,15237,10.0,5.6,1203.0,25.8
3,4,Angola,Angola,Sub-Saharan Africa,156,33,50.6,35.9,26.6,20.5,...,25.3,28.2,190.3,0.7,2.9,6753,8.2,31.7,-2254.5,65.3
4,5,Argentina,Argentina,Americas,148,26,52.2,47.8,44.5,33.5,...,41.0,44.1,920.2,2.9,0.7,20876,8.7,25.7,11857.0,52.6

In [144]:
print(inspector.get_table_names())

['free_ecos_4', 'united_nations_transformed', 'life_expectancy', 'world_happiness_15', 'world_happiness_16', 'world_happiness_17', 'country_db']