In [62]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
#Database Connection
engine = create_engine('postgresql://user:Angybix6355@localhost:5432/country_db')
#engine = create_engine('postgresql+psycopg2://localhost:5432/OO00ZZ33')
# url = 'postgresql://{user}:{passwd}@{host}:{port}/{db}'.format(
#user='postgres', passwd='Angybix6355', host='localhost', port='5432', db='country_db')
engine = create_engine(url)
connection = engine.connect()

### Extract CSVs into DataFrames

In [5]:
raw_file = "economic_freedom_index2019_data.csv"
free_eco_df = pd.read_csv(raw_file, encoding="ISO-8859-1")
free_eco_df.head()

,CountryID,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
0,1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
1,2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
2,3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
3,4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
4,5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6

In [6]:
free_eco_df.set_index('CountryID', inplace = True)
free_eco_df.head()

,Country Name,WEBNAME,Region,World Rank,Region Rank,2019 Score,Property Rights,Judical Effectiveness,Government Integrity,Tax Burden,...,Country,Population (Millions),"GDP (Billions, PPP)",GDP Growth Rate (%),5 Year GDP Growth Rate (%),GDP per Capita (PPP),Unemployment (%),Inflation (%),FDI Inflow (Millions),Public Debt (% of GDP)
CountryID,,,,,,,,,,,,,,,,,,,,,
1,Afghanistan,Afghanistan,Asia-Pacific,152.0,39.0,51.5,19.6,29.6,25.2,91.7,...,Afghanistan,35.5,$69.6,2.5,2.9,"$1,958",8.8,5.0,53.9,7.3
2,Albania,Albania,Europe,52.0,27.0,66.5,54.8,30.6,40.4,86.3,...,Albania,2.9,$36.0,3.9,2.5,"$12,507",13.9,2.0,"1,119.1",71.2
3,Algeria,Algeria,Middle East and North Africa,171.0,14.0,46.2,31.6,36.2,28.9,76.4,...,Algeria,41.5,$632.9,2.0,3.1,"$15,237",10.0,5.6,"1,203.0",25.8
4,Angola,Angola,Sub-Saharan Africa,156.0,33.0,50.6,35.9,26.6,20.5,83.9,...,Angola,28.2,$190.3,0.7,2.9,"$6,753",8.2,31.7,"-2,254.5",65.3
5,Argentina,Argentina,Americas,148.0,26.0,52.2,47.8,44.5,33.5,69.3,...,Argentina,44.1,$920.2,2.9,0.7,"$20,876",8.7,25.7,"11,857.0",52.6

In [17]:
free_eco_df.columns=free_eco_df.columns.str.replace('(','')
free_eco_df.columns=free_eco_df.columns.str.replace(')','')
free_eco_df.columns=free_eco_df.columns.str.replace('%','')
free_eco_df.columns=free_eco_df.columns.str.replace(',','')
free_eco_df.columns=free_eco_df.columns.str.replace(r"[\"\',]", '')
free_eco_df.columns =free_eco_df.columns.str.rstrip()
# test['Address 1'] = test['Address 1'].str.replace(r"[\"\',]", '')
# free_eco_df.head()
free_eco_df[free_eco_df.columns.drop('Country')]
free_eco_df.columns

Index(['Country Name', 'WEBNAME', 'Region', 'World Rank', 'Region Rank',
       '2019 Score', 'Property Rights', 'Judical Effectiveness',
       'Government Integrity', 'Tax Burden', 'Govt Spending', 'Fiscal Health',
       'Business Freedom', 'Labor Freedom', 'Monetary Freedom',
       'Trade Freedom', 'Investment Freedom', 'Financial Freedom',
       'Tariff Rate', 'Income Tax Rate', 'Corporate Tax Rate',
       'Tax Burden  of GDP', 'Govt Expenditure  of GDP', 'Country',
       'Population Millions', 'GDP Billions PPP', 'GDP Growth Rate',
       '5 Year GDP Growth Rate', 'GDP per Capita PPP', 'Unemployment',
       'Inflation', 'FDI Inflow Millions', 'Public Debt  of GDP'],
      dtype='object')

In [15]:
free_eco1_df= free_eco_df.rename(columns={  
            'Tax Burden  of GDP' :  'Tax Burdenof GDP', 
            'Public Debt  of GDP': 'Public Debtof GDP', 
            'Govt Expenditure  of GDP' :'Govt Expenditureof GDP'
            })

free_eco1_df.columns

Index(['Country Name', 'WEBNAME', 'Region', 'World Rank', 'Region Rank',
       '2019 Score', 'Property Rights', 'Judical Effectiveness',
       'Government Integrity', 'Tax Burden', 'Govt Spending', 'Fiscal Health',
       'Business Freedom', 'Labor Freedom', 'Monetary Freedom',
       'Trade Freedom', 'Investment Freedom', 'Financial Freedom',
       'Tariff Rate', 'Income Tax Rate', 'Corporate Tax Rate',
       'Tax Burdenof GDP', 'Govt Expenditureof GDP', 'Country',
       'Population Millions', 'GDP Billions PPP', 'GDP Growth Rate',
       '5 Year GDP Growth Rate', 'GDP per Capita PPP', 'Unemployment',
       'Inflation', 'FDI Inflow Millions', 'Public Debtof GDP'],
      dtype='object')

### Transform premise DataFrame

In [ ]:
# from sqlalchemy import Table, Column, Integer, String, MetaData
# meta = MetaData()
# students = Table(
#    'students', meta, 
#    Column('id', Integer, primary_key = True), 
#    Column('name', String), 
#    Column('lastname', String), 
# )
# meta.create_all(engine)

### Transform county DataFrame

In [ ]:
from sqlalchemy import Table, Column, Integer, String, MetaData, Float
meta = MetaData()
# precision=10,length=2
free_eco = Table(
    'free_eco', meta,
            Column('CountryID', Integer),
            Column('Country Name', String, primary_key = True), 
            Column('WEBNAME', String),
            Column('Region', String),
            Column('World Rank' ,Integer),
            Column('Region Rank', Integer),
            Column('2019 Score', Float(10,2)),
            Column('2019 Score', Float(10,2)),
            Column('Property Rights', Float(10, 2)),
            Column('Judical Effectiveness', Float(10, 2)),
            Column('Government Integrity', Float(10, 2)),
            Column('Tax Burden',  Float(10, 2)),
            Column('Govt Spending', Float(10, 2)),
            Column('Fiscal Health', Float(10, 2)),
            Column('Business Freedom', Float(10, 2)), 
            Column('Labor Freedom', Float(10, 2)),
            Column('Monetary Freedom', Float(10, 2)),
            Column('Trade Freedom', Float(10, 2)),
            Column('Investment Freedom', Float(10, 2)),
            Column('Financial Freedom', Float(10, 2)),
            Column('Trade Freedom', Float(10, 2)),
            Column('Investment Freedom', Float(10, 2)),
            Column('Financial Freedom', Float(10, 2)),
            Column('Tariff Rate', Float(10, 2)),
            Column('Income Tax Rate', Float(10, 2)),
            Column('Corporate Tax Rate', Float(10, 2)),
            Column('Tax Burdenof GDP', Float(10, 2)), 
            Column('Govt Expenditure of GDP', Float(10, 2)),
            Column('Country', Float(10, 2)),           
            Column('Population Millions', Float(10, 2)), 
            Column('GDP Billions PPP', Float(10, 2)), 
            Column('GDP Growth Rate', Float(10, 2)),
            Column('5 Year GDP Growth Rate', Float(10, 2)),
            Column('GDP per Capita PPP', Float(10, 2)),
            Column('Unemployment', Float(10, 2)),
            Column('Inflation', Float(10, 2)),
            Column('FDI Inflow Millions', Float(10, 2)),
            Column('Public Debtof GDP',  Float(10, 2))
            )

         
 

meta.create_all(engine)

### Create database connection

In [ ]:
engine.table_names()
free_eco1_df.to_sql(name='country_db', con=engine, if_exists='append', index=True)

In [ ]:
# Confirm tables

### Load DataFrames into database